Summary of outcomes:

div to ssh_cos only, batch_size=10
R2 from the best models in each run are:
[0.71200164 0.7092568  0.70846646 0.71314044]
corr from the best models in each run are:
[0.8454739  0.84274485 0.84231521 0.8457262 ]

vort to ssh_cos only, batch_size=10
R2 from the best models in each run are:
[0.83241847 0.82840353 0.82703668 0.82710327]
corr from the best models in each run are:
[0.91324089 0.91147217 0.91132234 0.91095138]

---------------------------------------------
div to ssh_cos and ssh_sin, batch_size=10
R2 from the best models in each run are:
[0.77560043 0.771282   0.77819786 0.7697045 ]
corr from the best models in each run are:
[0.88150735 0.88002645 0.8826575  0.87888121]


vort to ssh_cos and ssh_sin, batch_size=10
R2 from the best models in each run are:
[0.74091076 0.73678359 0.73939649 0.73511447]
corr from the best models in each run are:
[0.86151784 0.85899898 0.86089328 0.85819646]

---------------------------------------------
div to ssh_cos only, batch_size=100
R2 from the best models in each run are:
[0.70388961 0.69786856 0.70412668 0.69500771]
corr from the best models in each run are:
[0.84168713 0.83839298 0.84008428 0.83767132]

vort to ssh_cos only, batch_size=100
R2 from the best models in each run are:
[0.7655253  0.76617748 0.76492614 0.77463616]
corr from the best models in each run are:
[0.87496319 0.87541521 0.87478422 0.88030991]

---------------------------------------------

div to ssh_cos and ssh_sin, batch_size=100
R2 from the best models in each run are:
[0.76925564 0.76784907 0.7624617  0.76859775]
corr from the best models in each run are:
[0.87765357 0.87739345 0.87562212 0.87729587]


vort to ssh_cos and ssh_sin, batch_size=100
R2 from the best models in each run are:
[0.67702224 0.67874523 0.67075058 0.67682131]
corr from the best models in each run are:
[0.82337388 0.82430789 0.81952929 0.82334258]

In [1]:
#Previously I got weird results because my perforamnces from the vort and div run are the results of 
#Jeff's vort and div runs swapped. My run with (vort+div) is also slightly worse than Jeff's. Now I 
#try if I could reconstruct Jeff's results if I make the batch number to be 10 and make the output channel 
#to be ssh_cos, just like what Jeff did. 
#If these still don't agree with Jeff's results, then it is probably the batchnorm layer that's causing problems. 
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from netCDF4 import Dataset
from tqdm import tqdm
import torch.nn.functional as F
from sklearn.metrics import r2_score as R2
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score as r2
from copy import deepcopy
import utils
from unet import UNet_nobatchnorm
from scipy.stats import pearsonr
#JU's addtion to automate inputs and outputs
import helper_functions as hf
import os
def save_fn(var_input_list, var_output_list):
    var_input_join  = '_and_'.join(var_input_list)
    var_output_join = '_and_'.join(var_output_list)
    return '{}_to_{}'.format(var_input_join, var_output_join)
    
torch.cuda.set_device(0)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print ('Running on ', device)

Running on  cuda:0


In [2]:
torch.cuda.is_available()

True

In [3]:
print(torch.__version__)
print(torch.version.cuda)

2.5.1
12.6


In [4]:
maxEpochs =  300#small number is taken for debugging
nensemble = 4 #How many training sessions are run for each configuration ***
Nbase = 16

In [5]:
!nvidia-smi #GPU usage should be maxed out during training; tune batch_size according to that

Wed Apr  2 21:12:21 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:03:00.0 Off |                    0 |
| N/A   47C    P0             71W /  500W |       5MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [6]:
root_dir = '/work/uo0780/u241359/project_tide_synergy/data/'
nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

Ntrain = np.sum([nc.dimensions['time_counter'].size for nc in nctrains], axis = 0)
Ntest = np.sum([nc.dimensions['time_counter'].size for nc in nctest], axis = 0)

print('number of training records:', Ntrain)
print('number of testing records:', Ntest)

numTrainFiles = len(nctrains)
numRecsFile = nctrains[0].dimensions['time_counter'].size #How many snapshots in time in each data set there is
print (numRecsFile)

number of training records: 600
number of testing records: 150
150


In [7]:
def hwvorticity(u, v, dgrid = 4000):
    return (np.gradient(v, axis =2) - np.gradient(u, axis =1))/dgrid

def hwdivergence(u, v, dgrid = 4000):
    return (np.gradient(u, axis =2) + np.gradient(v, axis =1))/dgrid

def preload_data_vortdiv(nctrains, total_records):
    #total_records = Ntrain#sum(nc.dimensions['time_counter'].size for nc in nctrains)
    #dimensions of data of the nc file.
    max_height = 722
    max_width = 258
    all_input_data = np.zeros((total_records, N_inp, max_height, max_width))*np.nan
    all_output_data = np.zeros((total_records, N_out, max_height, max_width))*np.nan
    current_index = 0
    for ncindex, ncdata in enumerate(nctrains):
        num_recs = ncdata.dimensions['time_counter'].size #how many time stamps are there in each .nc file (i.e., at each turbulence level)
        rec_slice = slice(current_index, current_index + num_recs)
        for ind, var_name in enumerate(var_input_names):
            if var_name == 'vort':
                u = np.squeeze(ncdata.variables['u_xy_ins'])
                v = np.squeeze(ncdata.variables['v_xy_ins'])
                #u.shape: (150, 722, 257); v.shape: (150, 721, 258)
                #as u and v have different number of grid points in x and y, we truncate them so that their shapes agree, enabling the simple way to compute vorticities based on finite diff.
                data_slice = hwvorticity(u[:,:-1,:], v[:,:,:-1])
            elif var_name == 'div':
                u = np.squeeze(ncdata.variables['u_xy_ins'])
                v = np.squeeze(ncdata.variables['v_xy_ins'])
                data_slice = hwdivergence(u[:,:-1,:], v[:,:,:-1])
            else:           
                data_slice = np.squeeze(ncdata.variables[var_name])
            # print('data_slice shape:')
            # print(data_slice.shape)        
            #all_input_data[rec_slice, ind, :, :] = data_slice
            
            #For some variables, the dimensions in (x, y) may be smaller than (max_height, max_width). Changing the code so that it adapts them.
            # Get the actual dimensions of data_slice
            slice_height, slice_width = data_slice.shape[-2], data_slice.shape[-1]
            # Place data_slice into the corresponding slice of all_input_data
            all_input_data[rec_slice, ind, :slice_height, :slice_width] = data_slice
    

        for ind, var_name in enumerate(var_output_names):
            data_slice = np.squeeze(ncdata.variables[var_name])
            #all_output_data[rec_slice, ind, :, :] = data_slice
            # Get the actual dimensions of data_slice
            slice_height, slice_width = data_slice.shape[-2], data_slice.shape[-1]
            # Place data_slice into the corresponding slice of all_input_data
            all_output_data[rec_slice, ind, :slice_height, :slice_width] = data_slice

        current_index += num_recs
        
    return all_input_data, all_output_data
    


# Modify the loadtrain function to pull data from preloaded memory
def loaddata_preloaded_train(index, batch_size, all_input_data, all_output_data):
    rec_slice = slice(index, index + batch_size)
    lim = 720
    width = 256
    yslice = slice(0, lim)
    xslice = slice(0, width)
    # print('mean of squared values of loaded input data:')
    # print("{0:0.32f}".format(np.nanmean(all_input_data[rec_slice, :, yslice, xslice]**2)))
    return (all_input_data[rec_slice, :, yslice, xslice], 
            all_output_data[rec_slice, :, yslice, xslice])
#Load test data as one single batch
def loaddata_preloaded_test(all_input_data, all_output_data):
    #rec_slice = slice(index, index + batch_size)
    lim = 720
    width = 256
    yslice = slice(0, lim)
    xslice = slice(0, width)
    # print('rec_slice is:')
    # print(rec_slice)
    # print('mean of squared values of loaded input data:')
    # print("{0:0.32f}".format(np.nanmean(all_input_data[rec_slice, :, yslice, xslice]**2)))
    return (all_input_data[:, :, yslice, xslice], 
            all_output_data[:, :, yslice, xslice])



In [8]:
def run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all):
    ytest_slice = slice(0, 720)
    xtest_slice = slice(0, 256)
    rectest_slice = slice(0, 150)

    def totorch(x):
        return torch.tensor(x, dtype = torch.float).cuda()

    model = UNet_nobatchnorm(N_inp, N_out, bilinear = True, Nbase = Nbase).cuda()
    #model = torch.compile(UNet(N_inp, N_out, bilinear = True, Nbase = Nbase).cuda())

    if iensemble == 0:
        input = torch.randn(1,N_inp,256,720).to(device) 
        output = model(input)
        print('Model has ', utils.nparams(model)/1e6, ' million params')

    # for index in range(0, Ntrain, batch_size):
    #     inp, out = loadtrain_preloaded(index, batch_size, all_train_input, all_train_output)
    #     print(inp.shape, out.shape)
#         print(np.nanmean(inp**2), np.max(inp**2), inp.shape)
#         print(np.nanmean(out**2), np.max(out**2), inp.shape)

    inp_test, out_test = loaddata_preloaded_test(all_test_input, all_test_output)
    #inp, out_test = loadtest()
    # print('shapes of input and output TEST data:')
    # print(inp_test.shape, out_test.shape)
    with torch.no_grad():
        inp_test = totorch(inp_test)

    Tcycle = 10
    criterion_train  = nn.L1Loss()
    optim = torch.optim.AdamW(model.parameters(), lr=lr0, betas=(0.9, 0.999), eps=1e-8, weight_decay=1e-5*100) #increase weight_decay ***

    r2_test = np.zeros(maxEpochs)
    epochmin = []
    maxr2l = []

    learn = np.zeros(maxEpochs)
    minloss = 1000
    maxR2 = -1000
    minlosscount = 0
    perm = False

    model_best = deepcopy(model)  # Initialize before the loop for safety

    #print('Starting training loop')
    for epoch in tqdm(range(maxEpochs)):
        lr = utils.cosineSGDR(optim, epoch, T0=Tcycle, eta_min=0, eta_max=lr0, scheme = 'constant')  #captioning this seems to make the printed corr larger??***
        model.train()
        index_perm = np.arange(0, Ntrain, batch_size)
        
        if perm:
            index_perm = np.random.permutation(index_perm)
        
        for index in index_perm:
            inp, out = loaddata_preloaded_train(index, batch_size, all_train_input, all_train_output)            
#           inp, out = loadtrain(index, batch_size, nctrains)
            inp, out = totorch(inp), totorch(out)
            #continue #do this to pause the later operations to check how long it takes for the steps up to this 
            out_mod = model(inp)
            loss = criterion_train(out.squeeze(), out_mod.squeeze())
            #Set gradient to zero
            optim.zero_grad()
            #Compute gradients       
            loss.backward()
            #Update parameters with new gradient
            optim.step()
            #Record train loss
            #scheduler.step()
          
        model.eval()
        with torch.no_grad():
            #model_cpu = model.to('cpu')
            #out_mod = model_cpu(inp_test.to('cpu'))
            out_mod=model(inp_test)
            
            r2 = R2(out_test.flatten(), (out_mod).cpu().numpy().flatten())
            r2_test[epoch] = r2
            #print('Debugging: R2 of current epoch:', r2)#Debugging
            #record current best model and best predictions
            if maxR2 <  r2:
                maxR2 = r2
                epochmin.append(epoch)
                maxr2l.append(maxR2)                
                model_best = deepcopy(model)
                corr, pval = pearsonr(out_test.flatten(), (out_mod).cpu().numpy().flatten())
                print('R2:', r2, ' corr: ', corr, ' pval: ', pval)
            #model = model_cpu.to(device)

    #_, out_test = loadtest()
    model_best.eval()
    with torch.no_grad():
    #     inp_test = totorch(inp)
        model_best.to('cpu') #added by HW 
        out_mod = model_best(inp_test.to('cpu')).detach().cpu().numpy()

    R2_all[iensemble]=R2(out_test.flatten(), out_mod.flatten())
    corr_all[iensemble]=pearsonr(out_test.flatten(), out_mod.flatten())[0]
    # print('Best model R2:', R2_all[iensemble])#pearsonr(out_test.flatten(), out_mod.flatten())[0])
    # print('Best model corr:', corr_all[iensemble])#R2(out_test.flatten(), out_mod.flatten()))

    # Nx, Ny = out_test.shape[2:]; Nx, Ny

    # print(out_mod.shape, 'outout model shape')
    dr = '/work/uo0780/u241359/project_tide_synergy/trainedmodels' #'./models/to_vel'
    os.makedirs(dr, exist_ok=True) # exist_ok=True allows the function to do nothing (i.e., not raise an error) if the directory already exists.
    fstr = f'{save_fn_prefix}_rp_{iensemble}'
    PATH = dr + f'/{fstr}.pth'
    torch.save(model_best.state_dict(), PATH)

In [9]:
vi1 = 'vort'

vo1 = 'ssh_cos'

save_fn_prefix  = 'any_{}_{}_smallbatch_cosonly_nobatchnorm'.format(vi1, vo1)
var_input_names = [vi1]
var_output_names = [vo1]

batch_size = 10 

N_inp = len(var_input_names)
N_out = len(var_output_names)

lr0 = 0.005*10/batch_size #Roughly should scale inversely to batch_size

#Recording performance metrics on test data after eaching training cycle
R2_all = np.zeros(nensemble)
corr_all = np.zeros(nensemble)

nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

all_train_input, all_train_output = preload_data_vortdiv(nctrains, Ntrain)
all_test_input, all_test_output = preload_data_vortdiv(nctest, Ntest)

#Normalize data
#Compute mean and variance for normalization
mean_input=np.nanmean(np.concatenate((all_train_input, all_test_input), axis=0),axis=(0, 2, 3))
mean_output=np.nanmean(np.concatenate((all_train_output, all_test_output), axis=0),axis=(0, 2, 3))
#Subtract the data with their means
all_train_input=all_train_input-mean_input[None, :, None, None]
all_train_output=all_train_output-mean_output[None, :, None, None]
all_test_input=all_test_input-mean_input[None, :, None, None]
all_test_output=all_test_output-mean_output[None, :, None, None]
#Compute the variances
var_input=np.nanmean((np.concatenate((all_train_input, all_test_input), axis=0))**2,axis=(0, 2, 3))
var_output=np.nanmean((np.concatenate((all_train_output, all_test_output), axis=0))**2,axis=(0, 2, 3))
print("mean and variance of all input data:")
print(mean_input,var_input)
print("mean and variance of all output data:")
print(mean_output,var_output)
#Scale the data so that they have variance of 1
all_train_input=all_train_input/np.sqrt(var_input[None, :, None, None])
all_train_output=all_train_output/np.sqrt(var_output[None, :, None, None])
all_test_input=all_test_input/np.sqrt(var_input[None, :, None, None])
all_test_output=all_test_output/np.sqrt(var_output[None, :, None, None])
#Have checked that after these operations, the data is scaled to be zero mean and variance 1.

for iensemble in np.arange(nensemble):
    run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all)  
print('R2 from the best models in each run are:')
print(R2_all)
print('corr from the best models in each run are:')
print(corr_all)

mean and variance of all input data:
[-1.37220302e-09] [1.34097669e-10]
mean and variance of all output data:
[-0.00051623] [9.36516511e-05]
Model has  1.124401  million params


  0%|          | 1/300 [00:05<28:47,  5.78s/it]

R2: 0.3300754711813164  corr:  0.6478012855623372  pval:  0.0


  1%|          | 2/300 [00:11<27:51,  5.61s/it]

R2: 0.48199119151765124  corr:  0.7120104023719742  pval:  0.0


  1%|          | 3/300 [00:16<27:27,  5.55s/it]

R2: 0.5852011733038514  corr:  0.7687265538008207  pval:  0.0


  1%|▏         | 4/300 [00:22<27:19,  5.54s/it]

R2: 0.6718215947510608  corr:  0.8235885961200322  pval:  0.0


  2%|▏         | 5/300 [00:27<27:06,  5.52s/it]

R2: 0.7110248110332713  corr:  0.8458643080862316  pval:  0.0


  2%|▏         | 6/300 [00:33<27:38,  5.64s/it]

R2: 0.7216453067497648  corr:  0.8531559710359589  pval:  0.0


  2%|▏         | 7/300 [00:39<28:00,  5.74s/it]

R2: 0.7372946421925977  corr:  0.8589372549493961  pval:  0.0


  3%|▎         | 8/300 [00:45<28:03,  5.77s/it]

R2: 0.74090992092505  corr:  0.8611573035782587  pval:  0.0


  3%|▎         | 9/300 [00:52<29:41,  6.12s/it]

R2: 0.7514625755014603  corr:  0.8672361571870275  pval:  0.0


  3%|▎         | 10/300 [00:58<29:56,  6.20s/it]

R2: 0.7540131360758855  corr:  0.8685495693496921  pval:  0.0


  5%|▌         | 15/300 [01:26<27:55,  5.88s/it]

R2: 0.7738482974878464  corr:  0.8833299437853561  pval:  0.0


  5%|▌         | 16/300 [01:33<28:58,  6.12s/it]

R2: 0.7786597547514502  corr:  0.8852556153074186  pval:  0.0


  6%|▌         | 17/300 [01:41<31:20,  6.64s/it]

R2: 0.7899871748051736  corr:  0.8906591763772079  pval:  0.0


  6%|▌         | 18/300 [01:47<30:48,  6.56s/it]

R2: 0.7930719420366037  corr:  0.8915666260470613  pval:  0.0


  6%|▋         | 19/300 [01:53<30:04,  6.42s/it]

R2: 0.7986778585589115  corr:  0.8939891342329169  pval:  0.0


  8%|▊         | 25/300 [02:25<25:53,  5.65s/it]

R2: 0.8015664067836081  corr:  0.8982581357006073  pval:  0.0


  9%|▊         | 26/300 [02:31<26:22,  5.78s/it]

R2: 0.8056128662624131  corr:  0.9007142199695187  pval:  0.0


  9%|▉         | 27/300 [02:37<26:12,  5.76s/it]

R2: 0.8115989267686526  corr:  0.9025407321820532  pval:  0.0


  9%|▉         | 28/300 [02:43<26:07,  5.76s/it]

R2: 0.8155769482618906  corr:  0.9043850363033714  pval:  0.0


 10%|▉         | 29/300 [02:48<25:49,  5.72s/it]

R2: 0.8194697850257553  corr:  0.9058391477970047  pval:  0.0


 13%|█▎        | 38/300 [03:34<22:36,  5.18s/it]

R2: 0.8244608215415212  corr:  0.9098533237651256  pval:  0.0


 13%|█▎        | 39/300 [03:40<23:27,  5.39s/it]

R2: 0.8277584056912242  corr:  0.9106514098627146  pval:  0.0


 16%|█▌        | 48/300 [04:24<21:23,  5.10s/it]

R2: 0.8303121094938595  corr:  0.9127255260736227  pval:  0.0


 16%|█▋        | 49/300 [04:30<22:27,  5.37s/it]

R2: 0.8314879303300828  corr:  0.9127824158615638  pval:  0.0


 20%|█▉        | 59/300 [05:23<23:12,  5.78s/it]

R2: 0.8324207194597573  corr:  0.9132436833506976  pval:  0.0


  0%|          | 1/300 [00:05<29:14,  5.87s/it]

R2: 0.31062313994208957  corr:  0.6534381769588826  pval:  0.0


  1%|          | 2/300 [00:11<29:16,  5.90s/it]

R2: 0.5366903806121859  corr:  0.7352208855386013  pval:  0.0


  1%|          | 3/300 [00:17<29:08,  5.89s/it]

R2: 0.6168911986668137  corr:  0.7922502701823171  pval:  0.0


  1%|▏         | 4/300 [00:23<28:45,  5.83s/it]

R2: 0.6568677703870547  corr:  0.8128194727698986  pval:  0.0


  2%|▏         | 5/300 [00:29<28:20,  5.76s/it]

R2: 0.6889405532498715  corr:  0.8317410480582027  pval:  0.0


  2%|▏         | 6/300 [00:34<28:33,  5.83s/it]

R2: 0.7075511282176338  corr:  0.8435512287445893  pval:  0.0


  2%|▏         | 7/300 [00:41<28:56,  5.93s/it]

R2: 0.713053839309072  corr:  0.8452432181039587  pval:  0.0


  3%|▎         | 8/300 [00:46<28:45,  5.91s/it]

R2: 0.7208846149027691  corr:  0.8494832234541315  pval:  0.0


  3%|▎         | 9/300 [00:52<28:34,  5.89s/it]

R2: 0.7339193680590737  corr:  0.856727325942511  pval:  0.0


  3%|▎         | 10/300 [00:58<28:32,  5.91s/it]

R2: 0.7370557251771623  corr:  0.8589320601169947  pval:  0.0


  5%|▍         | 14/300 [01:20<27:16,  5.72s/it]

R2: 0.74396775174436  corr:  0.8728704273374569  pval:  0.0


  5%|▌         | 15/300 [01:26<27:19,  5.75s/it]

R2: 0.7655015024285483  corr:  0.8796173083350757  pval:  0.0


  5%|▌         | 16/300 [01:32<27:10,  5.74s/it]

R2: 0.7719512276541863  corr:  0.8811054748602413  pval:  0.0


  6%|▌         | 17/300 [01:38<27:12,  5.77s/it]

R2: 0.7802513265559612  corr:  0.8840682812526539  pval:  0.0


  6%|▌         | 18/300 [01:44<27:04,  5.76s/it]

R2: 0.7873192492168287  corr:  0.8881740642283513  pval:  0.0


  6%|▋         | 19/300 [01:49<26:44,  5.71s/it]

R2: 0.7904517512996178  corr:  0.8895755710175257  pval:  0.0


  7%|▋         | 20/300 [01:55<26:30,  5.68s/it]

R2: 0.7906242024175928  corr:  0.8895029883918464  pval:  0.0


  9%|▊         | 26/300 [02:25<24:19,  5.33s/it]

R2: 0.7941211415827879  corr:  0.8943669262657348  pval:  0.0


  9%|▉         | 27/300 [02:32<25:34,  5.62s/it]

R2: 0.7986952527746078  corr:  0.8967504729126664  pval:  0.0


  9%|▉         | 28/300 [02:38<26:07,  5.76s/it]

R2: 0.8092924336928561  corr:  0.9010696577054935  pval:  0.0


 10%|▉         | 29/300 [02:44<26:26,  5.85s/it]

R2: 0.8098329032373546  corr:  0.9006957768225788  pval:  0.0


 10%|█         | 30/300 [02:50<27:14,  6.05s/it]

R2: 0.81075318973112  corr:  0.9007919146325648  pval:  0.0


 13%|█▎        | 38/300 [03:32<23:10,  5.31s/it]

R2: 0.8194774189428605  corr:  0.9073856746416582  pval:  0.0


 13%|█▎        | 40/300 [03:43<23:17,  5.37s/it]

R2: 0.8204528724480209  corr:  0.9063249295636664  pval:  0.0


 16%|█▌        | 48/300 [04:22<21:26,  5.11s/it]

R2: 0.8265037703320361  corr:  0.9107355908327476  pval:  0.0


 19%|█▉        | 58/300 [05:10<20:03,  4.97s/it]

R2: 0.8283918850746277  corr:  0.9114715194454206  pval:  0.0


  0%|          | 1/300 [00:06<31:21,  6.29s/it]

R2: 0.26324210930269987  corr:  0.6642947325776034  pval:  0.0


  1%|          | 2/300 [00:12<30:38,  6.17s/it]

R2: 0.5525097890790249  corr:  0.748292128826585  pval:  0.0


  1%|          | 3/300 [00:18<30:40,  6.20s/it]

R2: 0.6049773504866042  corr:  0.7833354348040622  pval:  0.0


  1%|▏         | 4/300 [00:24<30:25,  6.17s/it]

R2: 0.6582841152138466  corr:  0.8126882276419937  pval:  0.0


  2%|▏         | 5/300 [00:31<30:35,  6.22s/it]

R2: 0.6751113203537167  corr:  0.8299794113617938  pval:  0.0


  2%|▏         | 6/300 [00:37<30:37,  6.25s/it]

R2: 0.7085816154576132  corr:  0.8429747004652989  pval:  0.0


  2%|▏         | 7/300 [00:43<30:52,  6.32s/it]

R2: 0.7297286364397967  corr:  0.8548917211232416  pval:  0.0


  3%|▎         | 9/300 [00:55<29:24,  6.06s/it]

R2: 0.7458068821389944  corr:  0.8642641667811795  pval:  0.0


  3%|▎         | 10/300 [01:01<30:01,  6.21s/it]

R2: 0.7464979912250109  corr:  0.8645639415841969  pval:  0.0


  4%|▍         | 13/300 [01:18<27:36,  5.77s/it]

R2: 0.7527596200297866  corr:  0.8709194726864775  pval:  0.0


  5%|▌         | 15/300 [01:29<27:34,  5.80s/it]

R2: 0.7664270215578778  corr:  0.8789243156816365  pval:  0.0


  5%|▌         | 16/300 [01:36<28:12,  5.96s/it]

R2: 0.7749073867215296  corr:  0.8828445189680174  pval:  0.0


  6%|▌         | 17/300 [01:42<28:42,  6.09s/it]

R2: 0.7766108397733507  corr:  0.883978110291692  pval:  0.0


  6%|▌         | 18/300 [01:48<29:11,  6.21s/it]

R2: 0.7857235206849522  corr:  0.8871579346739296  pval:  0.0


  6%|▋         | 19/300 [01:56<30:23,  6.49s/it]

R2: 0.7892050400113069  corr:  0.8886053010819396  pval:  0.0


  8%|▊         | 25/300 [02:28<26:19,  5.74s/it]

R2: 0.7946237515515001  corr:  0.8942441635924012  pval:  0.0


  9%|▊         | 26/300 [02:34<27:04,  5.93s/it]

R2: 0.7990156154252676  corr:  0.8962548936574087  pval:  0.0


  9%|▉         | 28/300 [02:45<26:11,  5.78s/it]

R2: 0.807859053853647  corr:  0.900087938632626  pval:  0.0


 10%|▉         | 29/300 [02:52<26:36,  5.89s/it]

R2: 0.8118135228602492  corr:  0.9014968973539749  pval:  0.0


 12%|█▏        | 36/300 [03:27<23:03,  5.24s/it]

R2: 0.8139501162699234  corr:  0.9038536270936376  pval:  0.0


 13%|█▎        | 38/300 [03:38<23:46,  5.44s/it]

R2: 0.8156531602066843  corr:  0.9058610278461041  pval:  0.0


 13%|█▎        | 39/300 [03:44<24:12,  5.56s/it]

R2: 0.8210739131346148  corr:  0.9070874704379192  pval:  0.0


 16%|█▋        | 49/300 [04:34<22:26,  5.37s/it]

R2: 0.8246083971761361  corr:  0.9093787379926404  pval:  0.0


 20%|█▉        | 59/300 [05:28<23:19,  5.81s/it]

R2: 0.8259821263769803  corr:  0.9104089863956875  pval:  0.0


 20%|██        | 60/300 [05:35<24:47,  6.20s/it]

R2: 0.826317516423274  corr:  0.909795121162364  pval:  0.0


 23%|██▎       | 68/300 [06:20<21:30,  5.56s/it]

R2: 0.8270358651023814  corr:  0.9113233278599576  pval:  0.0


  0%|          | 1/300 [00:06<33:57,  6.81s/it]

R2: 0.020712398078852723  corr:  0.6018963095413166  pval:  0.0


  1%|          | 2/300 [00:13<32:39,  6.57s/it]

R2: 0.5030760684817472  corr:  0.7136037579575012  pval:  0.0


  1%|          | 3/300 [00:19<32:47,  6.62s/it]

R2: 0.5587112057118562  corr:  0.7728545099246538  pval:  0.0


  1%|▏         | 4/300 [00:26<32:54,  6.67s/it]

R2: 0.6418251487636726  corr:  0.8057851933047214  pval:  0.0


  2%|▏         | 5/300 [00:32<31:53,  6.49s/it]

R2: 0.6694618568770812  corr:  0.822853178697464  pval:  0.0


  2%|▏         | 6/300 [00:38<30:31,  6.23s/it]

R2: 0.6965862894860847  corr:  0.8364335464328239  pval:  0.0


  2%|▏         | 7/300 [00:45<31:02,  6.36s/it]

R2: 0.7109171359494224  corr:  0.8446179005900619  pval:  0.0


  3%|▎         | 8/300 [00:51<30:38,  6.30s/it]

R2: 0.7280650063331826  corr:  0.8533120270654672  pval:  0.0


  3%|▎         | 9/300 [00:57<29:36,  6.11s/it]

R2: 0.7317736587955603  corr:  0.8561574766225987  pval:  0.0


  3%|▎         | 10/300 [01:02<28:58,  6.00s/it]

R2: 0.7373649851839057  corr:  0.8591147304296536  pval:  0.0


  4%|▍         | 12/300 [01:13<26:51,  5.59s/it]

R2: 0.74076458399359  corr:  0.8644329240750989  pval:  0.0


  4%|▍         | 13/300 [01:18<26:48,  5.60s/it]

R2: 0.7428557429498927  corr:  0.8686707713379086  pval:  0.0


  5%|▍         | 14/300 [01:24<27:15,  5.72s/it]

R2: 0.7616837114583433  corr:  0.8800899444840012  pval:  0.0


  5%|▌         | 15/300 [01:30<27:32,  5.80s/it]

R2: 0.7770137999475804  corr:  0.8824027617750859  pval:  0.0


  5%|▌         | 16/300 [01:36<27:23,  5.79s/it]

R2: 0.780266035208686  corr:  0.8849154248346814  pval:  0.0


  6%|▌         | 17/300 [01:45<31:43,  6.73s/it]

R2: 0.7842582409671768  corr:  0.8878216251260912  pval:  0.0


  6%|▌         | 18/300 [01:53<33:35,  7.15s/it]

R2: 0.7956966427114462  corr:  0.8922773492766866  pval:  0.0


  6%|▋         | 19/300 [02:00<32:54,  7.03s/it]

R2: 0.7971136061625932  corr:  0.893307791787879  pval:  0.0


  9%|▊         | 26/300 [02:35<23:46,  5.21s/it]

R2: 0.7981309945375951  corr:  0.8964770005710572  pval:  0.0


  9%|▉         | 27/300 [02:41<24:34,  5.40s/it]

R2: 0.798204163321384  corr:  0.8967343966063973  pval:  0.0


  9%|▉         | 28/300 [02:47<25:00,  5.52s/it]

R2: 0.8127861814242139  corr:  0.9023732088916181  pval:  0.0


 10%|▉         | 29/300 [02:53<25:13,  5.58s/it]

R2: 0.8148502314688144  corr:  0.9036838806894446  pval:  0.0


 13%|█▎        | 38/300 [03:37<22:25,  5.14s/it]

R2: 0.8175324553374002  corr:  0.9064708562177635  pval:  0.0


 13%|█▎        | 39/300 [03:43<23:21,  5.37s/it]

R2: 0.8235175435945012  corr:  0.9087952793657506  pval:  0.0


 16%|█▋        | 49/300 [04:32<21:53,  5.23s/it]

R2: 0.827096016490874  corr:  0.9109496769566994  pval:  0.0


100%|██████████| 300/300 [25:21<00:00,  5.07s/it]


R2 from the best models in each run are:
[0.83241847 0.82840353 0.82703668 0.82710327]
corr from the best models in each run are:
[0.91324089 0.91147217 0.91132234 0.91095138]


In [10]:
vi1 = 'vort'

vo1 = 'ssh_cos'
vo2 = 'ssh_sin'

save_fn_prefix  = 'any_{}_{}{}_smallbatch_nobatchnorm'.format(vi1, vo1, vo2)
var_input_names = [vi1]
var_output_names = [vo1, vo2]

batch_size = 10 

N_inp = len(var_input_names)
N_out = len(var_output_names)

lr0 = 0.005*10/batch_size #Roughly should scale inversely to batch_size

#Recording performance metrics on test data after eaching training cycle
R2_all = np.zeros(nensemble)
corr_all = np.zeros(nensemble)

nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

all_train_input, all_train_output = preload_data_vortdiv(nctrains, Ntrain)
all_test_input, all_test_output = preload_data_vortdiv(nctest, Ntest)

#Normalize data
#Compute mean and variance for normalization
mean_input=np.nanmean(np.concatenate((all_train_input, all_test_input), axis=0),axis=(0, 2, 3))
mean_output=np.nanmean(np.concatenate((all_train_output, all_test_output), axis=0),axis=(0, 2, 3))
#Subtract the data with their means
all_train_input=all_train_input-mean_input[None, :, None, None]
all_train_output=all_train_output-mean_output[None, :, None, None]
all_test_input=all_test_input-mean_input[None, :, None, None]
all_test_output=all_test_output-mean_output[None, :, None, None]
#Compute the variances
var_input=np.nanmean((np.concatenate((all_train_input, all_test_input), axis=0))**2,axis=(0, 2, 3))
var_output=np.nanmean((np.concatenate((all_train_output, all_test_output), axis=0))**2,axis=(0, 2, 3))
print("mean and variance of all input data:")
print(mean_input,var_input)
print("mean and variance of all output data:")
print(mean_output,var_output)
#Scale the data so that they have variance of 1
all_train_input=all_train_input/np.sqrt(var_input[None, :, None, None])
all_train_output=all_train_output/np.sqrt(var_output[None, :, None, None])
all_test_input=all_test_input/np.sqrt(var_input[None, :, None, None])
all_test_output=all_test_output/np.sqrt(var_output[None, :, None, None])
#Have checked that after these operations, the data is scaled to be zero mean and variance 1.

for iensemble in np.arange(nensemble):
    run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all)  
print('R2 from the best models in each run are:')
print(R2_all)
print('corr from the best models in each run are:')
print(corr_all)

mean and variance of all input data:
[-1.37220302e-09] [1.34097669e-10]
mean and variance of all output data:
[-5.16228102e-04 -9.83592627e-05] [9.36516511e-05 1.01456128e-04]
Model has  1.124418  million params


  0%|          | 1/300 [00:08<41:00,  8.23s/it]

R2: 0.3200812931689063  corr:  0.584117912115099  pval:  0.0


  1%|          | 2/300 [00:15<38:23,  7.73s/it]

R2: 0.45878502519845643  corr:  0.6830387965907372  pval:  0.0


  1%|          | 3/300 [00:23<38:35,  7.80s/it]

R2: 0.5305531998325176  corr:  0.7339382447832358  pval:  0.0


  1%|▏         | 4/300 [00:31<39:27,  8.00s/it]

R2: 0.5733653882784333  corr:  0.7588940381646699  pval:  0.0


  2%|▏         | 5/300 [00:39<39:31,  8.04s/it]

R2: 0.6044776406623444  corr:  0.7780463196167601  pval:  0.0


  2%|▏         | 6/300 [00:48<39:41,  8.10s/it]

R2: 0.6251550228846365  corr:  0.7914918397581909  pval:  0.0


  2%|▏         | 7/300 [00:56<39:57,  8.18s/it]

R2: 0.6399636027670909  corr:  0.8005666163046886  pval:  0.0


  3%|▎         | 9/300 [01:12<40:27,  8.34s/it]

R2: 0.6482994517273912  corr:  0.8054747825768991  pval:  0.0


  3%|▎         | 10/300 [01:21<41:13,  8.53s/it]

R2: 0.6565572721527282  corr:  0.8104773936350538  pval:  0.0


  4%|▍         | 13/300 [01:44<40:00,  8.36s/it]

R2: 0.6619613510989673  corr:  0.8167164684951291  pval:  0.0


  5%|▍         | 14/300 [01:52<39:32,  8.30s/it]

R2: 0.6780667521154111  corr:  0.8259839640662521  pval:  0.0


  5%|▌         | 15/300 [02:01<40:47,  8.59s/it]

R2: 0.685841159237546  corr:  0.8296630418760835  pval:  0.0


  6%|▌         | 17/300 [02:15<36:16,  7.69s/it]

R2: 0.6865254262643239  corr:  0.8306633688668663  pval:  0.0


  6%|▌         | 18/300 [02:22<35:59,  7.66s/it]

R2: 0.6999437892326248  corr:  0.8376850844114369  pval:  0.0


  6%|▋         | 19/300 [02:30<36:26,  7.78s/it]

R2: 0.7076767560909051  corr:  0.8417044122801512  pval:  0.0


  7%|▋         | 20/300 [02:38<36:02,  7.72s/it]

R2: 0.7086776609169774  corr:  0.8421498248599247  pval:  0.0


  9%|▉         | 28/300 [03:23<27:40,  6.10s/it]

R2: 0.7220930466129345  corr:  0.8516952889167003  pval:  0.0


 10%|▉         | 29/300 [03:30<29:16,  6.48s/it]

R2: 0.7310574669101129  corr:  0.8557142169510127  pval:  0.0


 10%|█         | 30/300 [03:38<30:23,  6.75s/it]

R2: 0.7318274850026192  corr:  0.8557877388574311  pval:  0.0


 13%|█▎        | 39/300 [04:29<27:13,  6.26s/it]

R2: 0.7367535534849498  corr:  0.8595770362830283  pval:  0.0


 13%|█▎        | 40/300 [04:37<29:14,  6.75s/it]

R2: 0.7402199264492938  corr:  0.8608065301226546  pval:  0.0


 17%|█▋        | 50/300 [05:34<25:26,  6.10s/it]

R2: 0.7409089242654083  corr:  0.8615176475439884  pval:  0.0


  0%|          | 1/300 [00:08<41:56,  8.42s/it]

R2: 0.2947978800952521  corr:  0.5750566144906829  pval:  0.0


  1%|          | 2/300 [00:16<41:03,  8.27s/it]

R2: 0.434262002946633  corr:  0.6777755316166384  pval:  0.0


  1%|          | 3/300 [00:24<40:30,  8.18s/it]

R2: 0.5349724238563569  corr:  0.7350629737349049  pval:  0.0


  1%|▏         | 4/300 [00:32<39:22,  7.98s/it]

R2: 0.5598549225302647  corr:  0.7521318861841021  pval:  0.0


  2%|▏         | 5/300 [00:39<38:27,  7.82s/it]

R2: 0.5890686345389005  corr:  0.7683102650660195  pval:  0.0


  2%|▏         | 6/300 [00:50<42:29,  8.67s/it]

R2: 0.6061822179491371  corr:  0.7787201601318328  pval:  0.0


  2%|▏         | 7/300 [00:59<43:27,  8.90s/it]

R2: 0.6215307323588315  corr:  0.788943130817712  pval:  0.0


  3%|▎         | 8/300 [01:07<42:04,  8.65s/it]

R2: 0.6295324649187695  corr:  0.7936749689089113  pval:  0.0


  3%|▎         | 9/300 [01:15<40:55,  8.44s/it]

R2: 0.6390459609554461  corr:  0.7995525783864729  pval:  0.0


  4%|▍         | 13/300 [01:39<32:21,  6.77s/it]

R2: 0.6490746631912014  corr:  0.8084169097878328  pval:  0.0


  5%|▍         | 14/300 [01:46<32:59,  6.92s/it]

R2: 0.6545710373821196  corr:  0.8163518870643961  pval:  0.0


  5%|▌         | 15/300 [01:55<35:07,  7.40s/it]

R2: 0.6684563813716469  corr:  0.8206599537901839  pval:  0.0


  5%|▌         | 16/300 [02:03<36:44,  7.76s/it]

R2: 0.6853131461371068  corr:  0.8281964764410147  pval:  0.0


  6%|▌         | 17/300 [02:12<37:45,  8.01s/it]

R2: 0.6930819074933987  corr:  0.8326348863620863  pval:  0.0


  6%|▌         | 18/300 [02:20<37:37,  8.01s/it]

R2: 0.6977724577539206  corr:  0.8353516013157458  pval:  0.0


  6%|▋         | 19/300 [02:28<37:37,  8.03s/it]

R2: 0.7001193652816382  corr:  0.83692829098136  pval:  0.0


  8%|▊         | 25/300 [03:10<34:08,  7.45s/it]

R2: 0.7044154962098479  corr:  0.8414835267293969  pval:  0.0


  9%|▊         | 26/300 [03:20<36:49,  8.06s/it]

R2: 0.7071394113807438  corr:  0.8415936690017496  pval:  0.0


  9%|▉         | 27/300 [03:29<38:39,  8.50s/it]

R2: 0.716230804102003  corr:  0.8466518888862046  pval:  0.0


  9%|▉         | 28/300 [03:37<37:56,  8.37s/it]

R2: 0.7200657963459514  corr:  0.8491553191219032  pval:  0.0


 10%|▉         | 29/300 [03:45<37:22,  8.27s/it]

R2: 0.7220444477645327  corr:  0.8503376656936412  pval:  0.0


 10%|█         | 30/300 [03:53<36:24,  8.09s/it]

R2: 0.72330086121202  corr:  0.8509445173214973  pval:  0.0


 12%|█▏        | 36/300 [04:29<29:13,  6.64s/it]

R2: 0.723707427993999  corr:  0.851516494294698  pval:  0.0


 12%|█▏        | 37/300 [04:37<30:22,  6.93s/it]

R2: 0.7253375802863455  corr:  0.8533059135535457  pval:  0.0


 13%|█▎        | 38/300 [04:45<31:11,  7.14s/it]

R2: 0.7288319122690463  corr:  0.8550722044916859  pval:  0.0


 13%|█▎        | 39/300 [04:52<31:36,  7.27s/it]

R2: 0.7314538924248448  corr:  0.8561190629624731  pval:  0.0


 13%|█▎        | 40/300 [05:00<32:29,  7.50s/it]

R2: 0.7332881970442848  corr:  0.8568783637860342  pval:  0.0


 16%|█▋        | 49/300 [05:57<29:53,  7.15s/it]

R2: 0.7338068272683576  corr:  0.8577744073866516  pval:  0.0


 17%|█▋        | 50/300 [06:05<31:37,  7.59s/it]

R2: 0.7367830952487067  corr:  0.8589983650228188  pval:  0.0


  0%|          | 1/300 [00:07<38:31,  7.73s/it]

R2: 0.2978231407068044  corr:  0.5785901278688684  pval:  0.0


  1%|          | 2/300 [00:15<38:53,  7.83s/it]

R2: 0.4796744578274097  corr:  0.6994149498362949  pval:  0.0


  1%|          | 3/300 [00:23<38:52,  7.85s/it]

R2: 0.5340824462053078  corr:  0.7336243560072646  pval:  0.0


  1%|▏         | 4/300 [00:35<47:19,  9.59s/it]

R2: 0.5724316777708388  corr:  0.7568453082754363  pval:  0.0


  2%|▏         | 5/300 [00:43<44:32,  9.06s/it]

R2: 0.5919397320866184  corr:  0.769874911229938  pval:  0.0


  2%|▏         | 6/300 [00:53<45:30,  9.29s/it]

R2: 0.6115209593056641  corr:  0.7832444993698409  pval:  0.0


  2%|▏         | 7/300 [01:02<44:02,  9.02s/it]

R2: 0.6204700843065459  corr:  0.7881905879263925  pval:  0.0


  3%|▎         | 9/300 [01:17<40:49,  8.42s/it]

R2: 0.6340295322931039  corr:  0.7964503626646443  pval:  0.0


  3%|▎         | 10/300 [01:26<42:26,  8.78s/it]

R2: 0.63577839805675  corr:  0.7977162440270668  pval:  0.0


  4%|▍         | 12/300 [01:43<40:40,  8.47s/it]

R2: 0.6398155805728949  corr:  0.800908130784228  pval:  0.0


  4%|▍         | 13/300 [01:50<39:23,  8.24s/it]

R2: 0.647470468925983  corr:  0.806586915503656  pval:  0.0


  5%|▍         | 14/300 [01:59<39:20,  8.25s/it]

R2: 0.6574932483971726  corr:  0.815108873290785  pval:  0.0


  5%|▌         | 15/300 [02:07<40:09,  8.46s/it]

R2: 0.6624896931712217  corr:  0.8210097246736363  pval:  0.0


  5%|▌         | 16/300 [02:15<38:55,  8.22s/it]

R2: 0.6749513973925441  corr:  0.8248059270368491  pval:  0.0


  6%|▌         | 17/300 [02:23<37:37,  7.98s/it]

R2: 0.6838966849559647  corr:  0.8279435368168563  pval:  0.0


  6%|▌         | 18/300 [02:30<36:37,  7.79s/it]

R2: 0.6862810845254188  corr:  0.8293481473513187  pval:  0.0


  6%|▋         | 19/300 [02:37<35:50,  7.65s/it]

R2: 0.69642520979774  corr:  0.8353095978035736  pval:  0.0


  9%|▊         | 26/300 [03:17<28:23,  6.22s/it]

R2: 0.7043718695525356  corr:  0.842305424477612  pval:  0.0


  9%|▉         | 27/300 [03:25<30:05,  6.61s/it]

R2: 0.709903198855215  corr:  0.8431392976309773  pval:  0.0


 10%|▉         | 29/300 [03:37<29:43,  6.58s/it]

R2: 0.7213067224488403  corr:  0.8505022400241  pval:  0.0


 10%|█         | 30/300 [03:45<31:06,  6.91s/it]

R2: 0.7217426323261317  corr:  0.8501929717552914  pval:  0.0


 13%|█▎        | 39/300 [04:41<28:12,  6.49s/it]

R2: 0.734122908088299  corr:  0.8580519871301828  pval:  0.0


 16%|█▋        | 49/300 [05:45<30:08,  7.21s/it]

R2: 0.7384078721299923  corr:  0.860882195885233  pval:  0.0


 17%|█▋        | 50/300 [05:54<31:25,  7.54s/it]

R2: 0.7394018024831108  corr:  0.860896402606826  pval:  0.0


  0%|          | 1/300 [00:08<40:38,  8.15s/it]

R2: 0.3321346893349395  corr:  0.6218875002609396  pval:  0.0


  1%|          | 2/300 [00:16<40:41,  8.19s/it]

R2: 0.5243126419961277  corr:  0.7285323911132013  pval:  0.0


  1%|          | 3/300 [00:24<41:17,  8.34s/it]

R2: 0.5595974930107862  corr:  0.7492228954080846  pval:  0.0


  1%|▏         | 4/300 [00:33<41:35,  8.43s/it]

R2: 0.5860605909971127  corr:  0.7663239478619128  pval:  0.0


  2%|▏         | 5/300 [00:41<41:20,  8.41s/it]

R2: 0.5964040329922966  corr:  0.7744994963460864  pval:  0.0


  2%|▏         | 6/300 [00:50<41:32,  8.48s/it]

R2: 0.6155047279113837  corr:  0.7852884304974161  pval:  0.0


  2%|▏         | 7/300 [00:58<41:06,  8.42s/it]

R2: 0.6164481646173838  corr:  0.786242041144153  pval:  0.0


  3%|▎         | 8/300 [01:07<41:15,  8.48s/it]

R2: 0.6280683243318943  corr:  0.7926756241131583  pval:  0.0


  3%|▎         | 9/300 [01:15<41:02,  8.46s/it]

R2: 0.6391076777198248  corr:  0.7994503857537388  pval:  0.0


  3%|▎         | 10/300 [01:24<41:55,  8.67s/it]

R2: 0.6394099350840914  corr:  0.8000225244041634  pval:  0.0


  4%|▎         | 11/300 [01:33<41:02,  8.52s/it]

R2: 0.6405832819071711  corr:  0.8009597808829387  pval:  0.0


  4%|▍         | 12/300 [01:42<41:41,  8.68s/it]

R2: 0.6476626085366937  corr:  0.8060961502339316  pval:  0.0


  4%|▍         | 13/300 [01:50<41:41,  8.72s/it]

R2: 0.6565963630937588  corr:  0.8133914573659518  pval:  0.0


  5%|▍         | 14/300 [01:59<40:47,  8.56s/it]

R2: 0.6662354216423474  corr:  0.8174829647715711  pval:  0.0


  5%|▌         | 15/300 [02:09<43:02,  9.06s/it]

R2: 0.6700672253398414  corr:  0.8193439992015048  pval:  0.0


  5%|▌         | 16/300 [02:17<41:17,  8.72s/it]

R2: 0.6863329474638152  corr:  0.8290027850653516  pval:  0.0


  6%|▌         | 18/300 [02:31<37:54,  8.07s/it]

R2: 0.6970152915943206  corr:  0.8360854188688897  pval:  0.0


  6%|▋         | 19/300 [02:39<37:18,  7.97s/it]

R2: 0.7029157939649271  corr:  0.8385242941421309  pval:  0.0


  9%|▊         | 26/300 [03:27<34:24,  7.53s/it]

R2: 0.7041616253839822  corr:  0.8425590252921125  pval:  0.0


  9%|▉         | 27/300 [03:35<35:21,  7.77s/it]

R2: 0.7136578326309052  corr:  0.8455026396370977  pval:  0.0


  9%|▉         | 28/300 [03:43<36:14,  8.00s/it]

R2: 0.7175977564453004  corr:  0.8490284646151355  pval:  0.0


 10%|▉         | 29/300 [03:53<37:45,  8.36s/it]

R2: 0.7238205609151129  corr:  0.851184334820781  pval:  0.0


 10%|█         | 30/300 [04:01<38:14,  8.50s/it]

R2: 0.7239735865528936  corr:  0.8512905389167005  pval:  0.0


 12%|█▏        | 37/300 [04:48<30:49,  7.03s/it]

R2: 0.7256565379414002  corr:  0.853218411404452  pval:  0.0


 13%|█▎        | 38/300 [04:59<36:50,  8.44s/it]

R2: 0.7264321658082018  corr:  0.8547651835129827  pval:  0.0


 13%|█▎        | 39/300 [05:08<37:35,  8.64s/it]

R2: 0.7307734483931128  corr:  0.8557113015634449  pval:  0.0


 13%|█▎        | 40/300 [05:17<37:21,  8.62s/it]

R2: 0.7331000826623325  corr:  0.8568140498519595  pval:  0.0


 17%|█▋        | 50/300 [06:15<25:41,  6.16s/it]

R2: 0.7351074332560181  corr:  0.8581949811645342  pval:  0.0


100%|██████████| 300/300 [31:57<00:00,  6.39s/it]


R2 from the best models in each run are:
[0.74091076 0.73678359 0.73939649 0.73511447]
corr from the best models in each run are:
[0.86151784 0.85899898 0.86089328 0.85819646]


In [11]:
vi1 = 'vort'

vo1 = 'ssh_cos'
vo2 = 'ssh_sin'

save_fn_prefix  = 'any_{}_{}{}_nobatchnorm'.format(vi1, vo1, vo2)
var_input_names = [vi1]
var_output_names = [vo1, vo2]

batch_size = 100

N_inp = len(var_input_names)
N_out = len(var_output_names)

lr0 = 0.005*10/batch_size #Roughly should scale inversely to batch_size

#Recording performance metrics on test data after eaching training cycle
R2_all = np.zeros(nensemble)
corr_all = np.zeros(nensemble)

nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

all_train_input, all_train_output = preload_data_vortdiv(nctrains, Ntrain)
all_test_input, all_test_output = preload_data_vortdiv(nctest, Ntest)

#Normalize data
#Compute mean and variance for normalization
mean_input=np.nanmean(np.concatenate((all_train_input, all_test_input), axis=0),axis=(0, 2, 3))
mean_output=np.nanmean(np.concatenate((all_train_output, all_test_output), axis=0),axis=(0, 2, 3))
#Subtract the data with their means
all_train_input=all_train_input-mean_input[None, :, None, None]
all_train_output=all_train_output-mean_output[None, :, None, None]
all_test_input=all_test_input-mean_input[None, :, None, None]
all_test_output=all_test_output-mean_output[None, :, None, None]
#Compute the variances
var_input=np.nanmean((np.concatenate((all_train_input, all_test_input), axis=0))**2,axis=(0, 2, 3))
var_output=np.nanmean((np.concatenate((all_train_output, all_test_output), axis=0))**2,axis=(0, 2, 3))
print("mean and variance of all input data:")
print(mean_input,var_input)
print("mean and variance of all output data:")
print(mean_output,var_output)
#Scale the data so that they have variance of 1
all_train_input=all_train_input/np.sqrt(var_input[None, :, None, None])
all_train_output=all_train_output/np.sqrt(var_output[None, :, None, None])
all_test_input=all_test_input/np.sqrt(var_input[None, :, None, None])
all_test_output=all_test_output/np.sqrt(var_output[None, :, None, None])
#Have checked that after these operations, the data is scaled to be zero mean and variance 1.

for iensemble in np.arange(nensemble):
    run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all)  
print('R2 from the best models in each run are:')
print(R2_all)
print('corr from the best models in each run are:')
print(corr_all)

mean and variance of all input data:
[-1.37220302e-09] [1.34097669e-10]
mean and variance of all output data:
[-5.16228102e-04 -9.83592627e-05] [9.36516511e-05 1.01456128e-04]
Model has  1.124418  million params


  0%|          | 1/300 [00:08<41:56,  8.42s/it]

R2: -0.011178770411394368  corr:  0.04058338544856324  pval:  0.0


  1%|          | 2/300 [00:16<40:25,  8.14s/it]

R2: 0.005340444541760414  corr:  0.12155742879410777  pval:  0.0


  1%|          | 3/300 [00:24<39:45,  8.03s/it]

R2: 0.04549487610401348  corr:  0.26530235024634224  pval:  0.0


  1%|▏         | 4/300 [00:32<39:09,  7.94s/it]

R2: 0.1094628181735211  corr:  0.4015144060405418  pval:  0.0


  2%|▏         | 5/300 [00:40<39:12,  7.98s/it]

R2: 0.1714497502844845  corr:  0.47313109338869186  pval:  0.0


  2%|▏         | 6/300 [00:47<38:35,  7.88s/it]

R2: 0.23321879360408115  corr:  0.527761621336519  pval:  0.0


  2%|▏         | 7/300 [00:55<38:04,  7.80s/it]

R2: 0.2733838639901318  corr:  0.5556446592662123  pval:  0.0


  3%|▎         | 8/300 [01:03<37:54,  7.79s/it]

R2: 0.3042110491404435  corr:  0.5792250094069863  pval:  0.0


  3%|▎         | 9/300 [01:11<37:48,  7.80s/it]

R2: 0.312374512377267  corr:  0.583970638017554  pval:  0.0


  3%|▎         | 10/300 [01:18<37:37,  7.79s/it]

R2: 0.3136206252591772  corr:  0.5841965105260143  pval:  0.0


  4%|▍         | 12/300 [01:31<34:49,  7.26s/it]

R2: 0.3605550197833842  corr:  0.6197295523516392  pval:  0.0


  4%|▍         | 13/300 [01:39<35:44,  7.47s/it]

R2: 0.4218957987221774  corr:  0.6604003870192467  pval:  0.0


  5%|▍         | 14/300 [01:47<35:54,  7.53s/it]

R2: 0.4291572915697409  corr:  0.6646155955412254  pval:  0.0


  5%|▌         | 16/300 [02:00<33:34,  7.09s/it]

R2: 0.4540232583679158  corr:  0.686064988783174  pval:  0.0


  6%|▌         | 17/300 [02:08<34:09,  7.24s/it]

R2: 0.45695168937855357  corr:  0.6961264143113041  pval:  0.0


  6%|▌         | 18/300 [02:15<34:00,  7.24s/it]

R2: 0.48094983872112806  corr:  0.707207597069313  pval:  0.0


  7%|▋         | 20/300 [02:28<32:25,  6.95s/it]

R2: 0.48377630958683915  corr:  0.709069533540269  pval:  0.0


  7%|▋         | 22/300 [02:41<31:42,  6.84s/it]

R2: 0.4945818078982477  corr:  0.7118148214758437  pval:  0.0


  8%|▊         | 23/300 [02:48<32:29,  7.04s/it]

R2: 0.5116240864898861  corr:  0.7291132855290919  pval:  0.0


  8%|▊         | 24/300 [02:57<34:28,  7.50s/it]

R2: 0.5318249540738829  corr:  0.7420844590096356  pval:  0.0


  8%|▊         | 25/300 [03:05<35:02,  7.65s/it]

R2: 0.5446292042336828  corr:  0.7492574208148872  pval:  0.0


  9%|▉         | 27/300 [03:18<32:45,  7.20s/it]

R2: 0.5559871933572377  corr:  0.7495651716754246  pval:  0.0


  9%|▉         | 28/300 [03:26<33:24,  7.37s/it]

R2: 0.5671541572085834  corr:  0.7648283498861886  pval:  0.0


 10%|▉         | 29/300 [03:34<34:04,  7.54s/it]

R2: 0.568034487845279  corr:  0.7622472784461455  pval:  0.0


 10%|█         | 30/300 [03:41<34:12,  7.60s/it]

R2: 0.568996994387984  corr:  0.7630213169850907  pval:  0.0


 11%|█         | 32/300 [03:55<32:42,  7.32s/it]

R2: 0.5747134296439923  corr:  0.762535405720319  pval:  0.0


 11%|█         | 33/300 [04:03<33:36,  7.55s/it]

R2: 0.5870195075194329  corr:  0.7746780041895592  pval:  0.0


 11%|█▏        | 34/300 [04:10<32:54,  7.42s/it]

R2: 0.5969367879548104  corr:  0.7796065832237928  pval:  0.0


 12%|█▏        | 35/300 [04:17<32:27,  7.35s/it]

R2: 0.6035849009426035  corr:  0.7805662374148379  pval:  0.0


 12%|█▏        | 37/300 [04:30<30:23,  6.93s/it]

R2: 0.6196265379141059  corr:  0.7889253389049747  pval:  0.0


 13%|█▎        | 38/300 [04:37<30:53,  7.07s/it]

R2: 0.6254369861414801  corr:  0.7936540124055577  pval:  0.0


 13%|█▎        | 39/300 [04:45<31:21,  7.21s/it]

R2: 0.6289250849904364  corr:  0.7951447875521357  pval:  0.0


 14%|█▍        | 43/300 [05:09<27:53,  6.51s/it]

R2: 0.6305768641435812  corr:  0.7951895760354721  pval:  0.0


 15%|█▌        | 46/300 [05:27<27:07,  6.41s/it]

R2: 0.6353686735090959  corr:  0.7978431911697581  pval:  0.0


 16%|█▌        | 48/300 [05:40<28:07,  6.70s/it]

R2: 0.6481823255974626  corr:  0.8050982890389309  pval:  0.0


 16%|█▋        | 49/300 [05:48<29:31,  7.06s/it]

R2: 0.6516956820919533  corr:  0.8082615279474042  pval:  0.0


 17%|█▋        | 50/300 [05:56<30:12,  7.25s/it]

R2: 0.6526525647310476  corr:  0.8085824258063478  pval:  0.0


 17%|█▋        | 52/300 [06:10<29:21,  7.10s/it]

R2: 0.6563797233033237  corr:  0.8102388216337082  pval:  0.0


 19%|█▉        | 58/300 [06:44<25:07,  6.23s/it]

R2: 0.6628574460099949  corr:  0.8145083823829303  pval:  0.0


 20%|█▉        | 59/300 [06:52<26:52,  6.69s/it]

R2: 0.6630301033712588  corr:  0.8144333707018755  pval:  0.0


 20%|██        | 60/300 [07:00<28:52,  7.22s/it]

R2: 0.6640641031686331  corr:  0.8149471287139286  pval:  0.0


 23%|██▎       | 69/300 [07:51<23:44,  6.17s/it]

R2: 0.6663846506811685  corr:  0.8163289292825842  pval:  0.0


 23%|██▎       | 70/300 [07:59<26:27,  6.90s/it]

R2: 0.6700271955220019  corr:  0.8186380608248894  pval:  0.0


 26%|██▋       | 79/300 [08:51<23:05,  6.27s/it]

R2: 0.6730507053264717  corr:  0.8206351832710571  pval:  0.0


 29%|██▉       | 88/300 [09:41<21:17,  6.03s/it]

R2: 0.6741633220008869  corr:  0.8212035895603592  pval:  0.0


 30%|██▉       | 89/300 [09:49<22:59,  6.54s/it]

R2: 0.6751048802033677  corr:  0.822122915654851  pval:  0.0


 33%|███▎      | 99/300 [10:45<21:03,  6.29s/it]

R2: 0.675915526316546  corr:  0.8230061596537825  pval:  0.0


 33%|███▎      | 100/300 [10:53<22:41,  6.81s/it]

R2: 0.6768886589368226  corr:  0.8232580512451602  pval:  0.0


 37%|███▋      | 110/300 [11:49<18:59,  6.00s/it]

R2: 0.6770320236608185  corr:  0.8233767745842828  pval:  0.0


  0%|          | 1/300 [00:07<37:36,  7.55s/it]

R2: -0.007989340233812259  corr:  0.05903724379159115  pval:  0.0


  1%|          | 2/300 [00:15<37:27,  7.54s/it]

R2: 0.027144525860002378  corr:  0.25360307456160586  pval:  0.0


  1%|          | 3/300 [00:22<36:53,  7.45s/it]

R2: 0.08475038147873815  corr:  0.34931871081781335  pval:  0.0


  1%|▏         | 4/300 [00:31<39:04,  7.92s/it]

R2: 0.13687764495718113  corr:  0.3956920008253885  pval:  0.0


  2%|▏         | 5/300 [00:38<37:44,  7.67s/it]

R2: 0.23263497152852464  corr:  0.5161044073063574  pval:  0.0


  2%|▏         | 6/300 [00:46<38:31,  7.86s/it]

R2: 0.32310056774194673  corr:  0.5975938755021469  pval:  0.0


  2%|▏         | 7/300 [00:54<38:21,  7.85s/it]

R2: 0.3758229127315751  corr:  0.6397346160997812  pval:  0.0


  3%|▎         | 8/300 [01:02<37:56,  7.80s/it]

R2: 0.4081472627796999  corr:  0.6604857730203302  pval:  0.0


  3%|▎         | 9/300 [01:10<38:18,  7.90s/it]

R2: 0.421231408793896  corr:  0.6700064432294344  pval:  0.0


  3%|▎         | 10/300 [01:17<38:01,  7.87s/it]

R2: 0.42690558651280974  corr:  0.6734406647835786  pval:  0.0


  4%|▍         | 12/300 [01:31<35:01,  7.30s/it]

R2: 0.48886351400449546  corr:  0.7061915657776875  pval:  0.0


  4%|▍         | 13/300 [01:39<35:54,  7.51s/it]

R2: 0.5026065314597813  corr:  0.7209767201935126  pval:  0.0


  5%|▍         | 14/300 [01:46<36:07,  7.58s/it]

R2: 0.5255652831891141  corr:  0.7300604773083427  pval:  0.0


  5%|▌         | 15/300 [01:54<35:39,  7.51s/it]

R2: 0.5411556902639414  corr:  0.7422518838774895  pval:  0.0


  5%|▌         | 16/300 [02:01<35:28,  7.50s/it]

R2: 0.5448965026871906  corr:  0.7436688035319335  pval:  0.0


  6%|▌         | 17/300 [02:08<35:12,  7.47s/it]

R2: 0.551842329855822  corr:  0.7495157688516934  pval:  0.0


  6%|▌         | 18/300 [02:16<34:41,  7.38s/it]

R2: 0.560735607952837  corr:  0.758053286352677  pval:  0.0


  6%|▋         | 19/300 [02:23<35:04,  7.49s/it]

R2: 0.566970678054709  corr:  0.7594772870364177  pval:  0.0


  7%|▋         | 20/300 [02:31<35:09,  7.53s/it]

R2: 0.5675101155991158  corr:  0.7594711983558372  pval:  0.0


  7%|▋         | 22/300 [02:45<33:37,  7.26s/it]

R2: 0.5701840270718112  corr:  0.7608893011487665  pval:  0.0


  8%|▊         | 23/300 [02:53<34:38,  7.50s/it]

R2: 0.588965244488745  corr:  0.7689154855922622  pval:  0.0


  8%|▊         | 24/300 [03:01<35:12,  7.65s/it]

R2: 0.598588619745505  corr:  0.7758417050165723  pval:  0.0


  9%|▊         | 26/300 [03:14<32:45,  7.17s/it]

R2: 0.6208816771217701  corr:  0.7890011850707889  pval:  0.0


 10%|▉         | 29/300 [03:33<30:31,  6.76s/it]

R2: 0.6257282401495255  corr:  0.7913409243734235  pval:  0.0


 10%|█         | 30/300 [03:40<31:25,  6.98s/it]

R2: 0.6263991976933773  corr:  0.792291082384404  pval:  0.0


 11%|█▏        | 34/300 [04:04<29:19,  6.61s/it]

R2: 0.6342631151959546  corr:  0.7988218926100286  pval:  0.0


 12%|█▏        | 36/300 [04:18<29:34,  6.72s/it]

R2: 0.6363699185560582  corr:  0.7990859801513579  pval:  0.0


 13%|█▎        | 38/300 [04:31<29:51,  6.84s/it]

R2: 0.6512933992087819  corr:  0.8073390697642262  pval:  0.0


 16%|█▋        | 49/300 [05:32<25:25,  6.08s/it]

R2: 0.6623468658705167  corr:  0.8138600400942195  pval:  0.0


 17%|█▋        | 50/300 [05:40<28:00,  6.72s/it]

R2: 0.6630802522568916  corr:  0.8143392066997069  pval:  0.0


 20%|█▉        | 59/300 [06:32<25:09,  6.26s/it]

R2: 0.6652541237693714  corr:  0.8159836332618224  pval:  0.0


 20%|██        | 60/300 [06:40<27:09,  6.79s/it]

R2: 0.6670558078598767  corr:  0.8169155955602961  pval:  0.0


 23%|██▎       | 68/300 [07:26<24:07,  6.24s/it]

R2: 0.6686230106518716  corr:  0.8184345472571254  pval:  0.0


 23%|██▎       | 69/300 [07:33<25:36,  6.65s/it]

R2: 0.6716244482444373  corr:  0.8197114631186252  pval:  0.0


 23%|██▎       | 70/300 [07:41<26:41,  6.96s/it]

R2: 0.6726285292857079  corr:  0.8203702044931905  pval:  0.0


 26%|██▋       | 79/300 [08:32<22:39,  6.15s/it]

R2: 0.6728720259359833  corr:  0.8213940801853814  pval:  0.0


 27%|██▋       | 80/300 [08:40<24:33,  6.70s/it]

R2: 0.6746823361330982  corr:  0.8219859241378272  pval:  0.0


 29%|██▉       | 88/300 [09:27<22:34,  6.39s/it]

R2: 0.6787410518486767  corr:  0.824308124075607  pval:  0.0


  0%|          | 1/300 [00:08<41:14,  8.28s/it]

R2: -0.000777098851822533  corr:  0.07032423306390151  pval:  0.0


  1%|          | 2/300 [00:16<41:18,  8.32s/it]

R2: 0.019837083565563463  corr:  0.16809579851234402  pval:  0.0


  1%|          | 3/300 [00:24<41:01,  8.29s/it]

R2: 0.05033721575314953  corr:  0.25602611201909337  pval:  0.0


  1%|▏         | 4/300 [00:33<40:53,  8.29s/it]

R2: 0.09983856380677236  corr:  0.34249725819922455  pval:  0.0


  2%|▏         | 5/300 [00:41<40:22,  8.21s/it]

R2: 0.16526211914933742  corr:  0.4276151471087263  pval:  0.0


  2%|▏         | 6/300 [00:49<39:42,  8.10s/it]

R2: 0.3311280917223077  corr:  0.6101194118190181  pval:  0.0


  2%|▏         | 7/300 [00:56<38:58,  7.98s/it]

R2: 0.4076407569651762  corr:  0.659567599076019  pval:  0.0


  3%|▎         | 8/300 [01:04<38:30,  7.91s/it]

R2: 0.43346758739877744  corr:  0.673919339461334  pval:  0.0


  3%|▎         | 9/300 [01:12<37:57,  7.83s/it]

R2: 0.44661783095856633  corr:  0.6803052311493772  pval:  0.0


  3%|▎         | 10/300 [01:20<37:48,  7.82s/it]

R2: 0.45040585797859345  corr:  0.6816444277821765  pval:  0.0


  4%|▎         | 11/300 [01:27<37:26,  7.77s/it]

R2: 0.4776115838898545  corr:  0.7017524573349364  pval:  0.0


  4%|▍         | 12/300 [01:35<37:16,  7.77s/it]

R2: 0.49933343382074125  corr:  0.7167701228335546  pval:  0.0


  4%|▍         | 13/300 [01:43<37:07,  7.76s/it]

R2: 0.5263460429850624  corr:  0.7284986524558582  pval:  0.0


  5%|▍         | 14/300 [01:51<37:17,  7.82s/it]

R2: 0.5441254735456871  corr:  0.7394222533586013  pval:  0.0


  5%|▌         | 15/300 [01:58<36:47,  7.75s/it]

R2: 0.5624503912345156  corr:  0.7507547125741928  pval:  0.0


  5%|▌         | 16/300 [02:06<36:53,  7.79s/it]

R2: 0.5654605891247859  corr:  0.7525085435478116  pval:  0.0


  6%|▌         | 17/300 [02:14<37:04,  7.86s/it]

R2: 0.5662961830647816  corr:  0.7530335247899405  pval:  0.0


  6%|▌         | 18/300 [02:22<36:38,  7.79s/it]

R2: 0.5798806751564316  corr:  0.7622602498425987  pval:  0.0


  6%|▋         | 19/300 [02:30<36:53,  7.88s/it]

R2: 0.5805585560781916  corr:  0.763294907358642  pval:  0.0


  7%|▋         | 20/300 [02:38<36:46,  7.88s/it]

R2: 0.5818336251174936  corr:  0.7642471594626373  pval:  0.0


  7%|▋         | 22/300 [02:51<34:19,  7.41s/it]

R2: 0.5864042051638787  corr:  0.766713158001095  pval:  0.0


  8%|▊         | 23/300 [02:59<34:53,  7.56s/it]

R2: 0.5877561474863903  corr:  0.7671488235964984  pval:  0.0


  8%|▊         | 24/300 [03:07<35:32,  7.73s/it]

R2: 0.5916357979366129  corr:  0.7696679167104967  pval:  0.0


  8%|▊         | 25/300 [03:15<35:40,  7.78s/it]

R2: 0.6009901739808605  corr:  0.7766112974791513  pval:  0.0


  9%|▊         | 26/300 [03:23<35:56,  7.87s/it]

R2: 0.6089261614013888  corr:  0.7846637910470963  pval:  0.0


  9%|▉         | 28/300 [03:37<33:35,  7.41s/it]

R2: 0.6270768914543468  corr:  0.7919947225079176  pval:  0.0


 10%|█         | 30/300 [03:50<31:36,  7.03s/it]

R2: 0.6292180715492677  corr:  0.7932353997025031  pval:  0.0


 12%|█▏        | 37/300 [04:31<28:31,  6.51s/it]

R2: 0.6393893136370852  corr:  0.7998595901462409  pval:  0.0


 13%|█▎        | 38/300 [04:38<30:02,  6.88s/it]

R2: 0.6451844149036798  corr:  0.8039116887986039  pval:  0.0


 13%|█▎        | 39/300 [04:46<31:22,  7.21s/it]

R2: 0.6490609571703432  corr:  0.8057731749472301  pval:  0.0


 16%|█▌        | 47/300 [05:31<25:53,  6.14s/it]

R2: 0.6502433735941078  corr:  0.8078447122484945  pval:  0.0


 16%|█▌        | 48/300 [05:39<27:59,  6.66s/it]

R2: 0.6544847448401425  corr:  0.8092826561470597  pval:  0.0


 16%|█▋        | 49/300 [05:47<29:18,  7.00s/it]

R2: 0.6599662954151769  corr:  0.8128144882596501  pval:  0.0


 17%|█▋        | 50/300 [05:55<30:19,  7.28s/it]

R2: 0.6604289304681714  corr:  0.8129172452954677  pval:  0.0


 19%|█▉        | 58/300 [06:40<24:55,  6.18s/it]

R2: 0.6636094482846902  corr:  0.814766511873948  pval:  0.0


 20%|██        | 60/300 [06:54<26:54,  6.73s/it]

R2: 0.6649924570265597  corr:  0.8157151413103324  pval:  0.0


 22%|██▏       | 67/300 [07:36<25:49,  6.65s/it]

R2: 0.6653184989261804  corr:  0.8160858055761114  pval:  0.0


 23%|██▎       | 68/300 [07:44<27:08,  7.02s/it]

R2: 0.6659065864835503  corr:  0.8169636671802011  pval:  0.0


 23%|██▎       | 69/300 [07:52<27:55,  7.25s/it]

R2: 0.666296270271296  corr:  0.8172202927891677  pval:  0.0


 23%|██▎       | 70/300 [08:00<29:06,  7.60s/it]

R2: 0.6684437134991594  corr:  0.8181615076278465  pval:  0.0


 30%|███       | 90/300 [09:49<21:04,  6.02s/it]

R2: 0.6686074638681014  corr:  0.8185553106646248  pval:  0.0


 33%|███▎      | 99/300 [10:40<20:20,  6.07s/it]

R2: 0.6701050999764167  corr:  0.8187178395290066  pval:  0.0


 33%|███▎      | 100/300 [10:47<21:41,  6.51s/it]

R2: 0.6703301501253454  corr:  0.8194863131795855  pval:  0.0


 37%|███▋      | 110/300 [11:44<19:32,  6.17s/it]

R2: 0.6707717223519831  corr:  0.8195397671166245  pval:  0.0


  0%|          | 1/300 [00:08<40:22,  8.10s/it]

R2: -0.0194880038757812  corr:  0.0287685751360718  pval:  0.0


  1%|          | 2/300 [00:16<39:52,  8.03s/it]

R2: 0.01858185981281102  corr:  0.1377753711805858  pval:  0.0


  1%|          | 3/300 [00:24<40:12,  8.12s/it]

R2: 0.06349685109755698  corr:  0.26487224763657763  pval:  0.0


  1%|▏         | 4/300 [00:31<38:53,  7.88s/it]

R2: 0.13920863663676586  corr:  0.3825352524096242  pval:  0.0


  2%|▏         | 5/300 [00:39<39:13,  7.98s/it]

R2: 0.2316920931113452  corr:  0.48907540142159794  pval:  0.0


  2%|▏         | 6/300 [00:48<39:41,  8.10s/it]

R2: 0.3392788798441484  corr:  0.5905707668156525  pval:  0.0


  2%|▏         | 7/300 [00:56<40:05,  8.21s/it]

R2: 0.3826461764588096  corr:  0.6229914142563023  pval:  0.0


  3%|▎         | 8/300 [01:04<39:30,  8.12s/it]

R2: 0.41209198772957356  corr:  0.6455953428223404  pval:  0.0


  3%|▎         | 9/300 [01:12<39:04,  8.06s/it]

R2: 0.41247467315242425  corr:  0.646005915183556  pval:  0.0


  3%|▎         | 10/300 [01:20<38:12,  7.90s/it]

R2: 0.416633630133167  corr:  0.6487702479018218  pval:  0.0


  4%|▍         | 12/300 [01:32<34:10,  7.12s/it]

R2: 0.4709066718765309  corr:  0.6883696030393077  pval:  0.0


  4%|▍         | 13/300 [01:40<35:10,  7.35s/it]

R2: 0.5003244007751155  corr:  0.7094863664320528  pval:  0.0


  5%|▍         | 14/300 [01:47<35:05,  7.36s/it]

R2: 0.5227226209628326  corr:  0.7255220044854974  pval:  0.0


  5%|▌         | 15/300 [01:56<36:16,  7.64s/it]

R2: 0.5239310993661067  corr:  0.7308397407500851  pval:  0.0


  5%|▌         | 16/300 [02:04<36:51,  7.79s/it]

R2: 0.5429164186788403  corr:  0.7374864988170778  pval:  0.0


  6%|▌         | 18/300 [02:17<33:58,  7.23s/it]

R2: 0.5539705322870412  corr:  0.7459860329905604  pval:  0.0


  6%|▋         | 19/300 [02:24<34:03,  7.27s/it]

R2: 0.5559736304456229  corr:  0.7488569117595767  pval:  0.0


  7%|▋         | 20/300 [02:32<34:57,  7.49s/it]

R2: 0.5583785902613061  corr:  0.7497194048445708  pval:  0.0


  7%|▋         | 22/300 [02:46<34:20,  7.41s/it]

R2: 0.5684090235075943  corr:  0.7541380488131214  pval:  0.0


  8%|▊         | 24/300 [02:59<32:04,  6.97s/it]

R2: 0.5789040871855367  corr:  0.7616247018414326  pval:  0.0


  9%|▊         | 26/300 [03:12<31:22,  6.87s/it]

R2: 0.599477034145971  corr:  0.7752778240331698  pval:  0.0


  9%|▉         | 27/300 [03:21<33:20,  7.33s/it]

R2: 0.6042938118875888  corr:  0.7773651705637411  pval:  0.0


  9%|▉         | 28/300 [03:29<34:03,  7.51s/it]

R2: 0.6117051972353142  corr:  0.7823276458144744  pval:  0.0


 10%|▉         | 29/300 [03:36<34:03,  7.54s/it]

R2: 0.6154498221279312  corr:  0.7847471418740324  pval:  0.0


 10%|█         | 30/300 [03:44<34:46,  7.73s/it]

R2: 0.6162567768717055  corr:  0.7853890685705406  pval:  0.0


 11%|█         | 32/300 [03:58<32:27,  7.27s/it]

R2: 0.6205140268065988  corr:  0.7880810079298606  pval:  0.0


 12%|█▏        | 35/300 [04:17<30:30,  6.91s/it]

R2: 0.6241040191379801  corr:  0.7911025821324602  pval:  0.0


 12%|█▏        | 37/300 [04:31<30:57,  7.06s/it]

R2: 0.6353556484423539  corr:  0.7993347052177475  pval:  0.0


 13%|█▎        | 38/300 [04:39<31:58,  7.32s/it]

R2: 0.6367313373419263  corr:  0.798595451604572  pval:  0.0


 13%|█▎        | 39/300 [04:47<32:28,  7.47s/it]

R2: 0.64073650015863  corr:  0.8011847971332716  pval:  0.0


 13%|█▎        | 40/300 [04:55<32:53,  7.59s/it]

R2: 0.6427275021641992  corr:  0.8020386434335077  pval:  0.0


 15%|█▌        | 46/300 [05:30<27:25,  6.48s/it]

R2: 0.6461678463080632  corr:  0.8044410814280659  pval:  0.0


 16%|█▌        | 48/300 [05:43<27:50,  6.63s/it]

R2: 0.6474061856180595  corr:  0.8061437494763758  pval:  0.0


 16%|█▋        | 49/300 [05:51<29:27,  7.04s/it]

R2: 0.6538179580958683  corr:  0.8092358691348313  pval:  0.0


 17%|█▋        | 50/300 [05:59<30:19,  7.28s/it]

R2: 0.6562034773592902  corr:  0.8103017077625279  pval:  0.0


 19%|█▉        | 58/300 [06:45<25:17,  6.27s/it]

R2: 0.6577058366195268  corr:  0.8124789984613557  pval:  0.0


 20%|█▉        | 59/300 [06:53<27:02,  6.73s/it]

R2: 0.6615471649221912  corr:  0.8137876778232931  pval:  0.0


 20%|██        | 60/300 [07:01<28:19,  7.08s/it]

R2: 0.6634291030258237  corr:  0.8148352135482583  pval:  0.0


 23%|██▎       | 70/300 [07:57<23:16,  6.07s/it]

R2: 0.6666385228212244  corr:  0.8170797619835491  pval:  0.0


 26%|██▌       | 77/300 [08:37<22:41,  6.11s/it]

R2: 0.6712324056331356  corr:  0.8200821499821508  pval:  0.0


 26%|██▋       | 79/300 [08:51<24:22,  6.62s/it]

R2: 0.6722057040222313  corr:  0.8199107336163753  pval:  0.0


 27%|██▋       | 80/300 [08:59<25:45,  7.03s/it]

R2: 0.6726802964450966  corr:  0.8202600431783761  pval:  0.0


 30%|██▉       | 89/300 [09:49<21:43,  6.18s/it]

R2: 0.6727309311158454  corr:  0.8209359446622787  pval:  0.0


 33%|███▎      | 100/300 [10:51<20:37,  6.19s/it]

R2: 0.6733139712443355  corr:  0.8212084558660318  pval:  0.0


 37%|███▋      | 110/300 [11:48<19:57,  6.30s/it]

R2: 0.6733617350207595  corr:  0.8212720044167575  pval:  0.0


 40%|███▉      | 119/300 [12:39<18:23,  6.10s/it]

R2: 0.6768293110399863  corr:  0.8233434153478864  pval:  0.0


100%|██████████| 300/300 [28:55<00:00,  5.79s/it]


R2 from the best models in each run are:
[0.67702224 0.67874523 0.67075058 0.67682131]
corr from the best models in each run are:
[0.82337388 0.82430789 0.81952929 0.82334258]


In [12]:
vi1 = 'vort'

vo1 = 'ssh_cos'

save_fn_prefix  = 'any_{}_{}_cosonly_nobatchnorm'.format(vi1, vo1)
var_input_names = [vi1]
var_output_names = [vo1]

batch_size = 100

N_inp = len(var_input_names)
N_out = len(var_output_names)

lr0 = 0.005*10/batch_size #Roughly should scale inversely to batch_size

#Recording performance metrics on test data after eaching training cycle
R2_all = np.zeros(nensemble)
corr_all = np.zeros(nensemble)

nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

all_train_input, all_train_output = preload_data_vortdiv(nctrains, Ntrain)
all_test_input, all_test_output = preload_data_vortdiv(nctest, Ntest)

#Normalize data
#Compute mean and variance for normalization
mean_input=np.nanmean(np.concatenate((all_train_input, all_test_input), axis=0),axis=(0, 2, 3))
mean_output=np.nanmean(np.concatenate((all_train_output, all_test_output), axis=0),axis=(0, 2, 3))
#Subtract the data with their means
all_train_input=all_train_input-mean_input[None, :, None, None]
all_train_output=all_train_output-mean_output[None, :, None, None]
all_test_input=all_test_input-mean_input[None, :, None, None]
all_test_output=all_test_output-mean_output[None, :, None, None]
#Compute the variances
var_input=np.nanmean((np.concatenate((all_train_input, all_test_input), axis=0))**2,axis=(0, 2, 3))
var_output=np.nanmean((np.concatenate((all_train_output, all_test_output), axis=0))**2,axis=(0, 2, 3))
print("mean and variance of all input data:")
print(mean_input,var_input)
print("mean and variance of all output data:")
print(mean_output,var_output)
#Scale the data so that they have variance of 1
all_train_input=all_train_input/np.sqrt(var_input[None, :, None, None])
all_train_output=all_train_output/np.sqrt(var_output[None, :, None, None])
all_test_input=all_test_input/np.sqrt(var_input[None, :, None, None])
all_test_output=all_test_output/np.sqrt(var_output[None, :, None, None])
#Have checked that after these operations, the data is scaled to be zero mean and variance 1.

for iensemble in np.arange(nensemble):
    run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all)  
print('R2 from the best models in each run are:')
print(R2_all)
print('corr from the best models in each run are:')
print(corr_all)

mean and variance of all input data:
[-1.37220302e-09] [1.34097669e-10]
mean and variance of all output data:
[-0.00051623] [9.36516511e-05]
Model has  1.124401  million params


  0%|          | 1/300 [00:05<28:03,  5.63s/it]

R2: 0.023123469202038893  corr:  0.4015050658494753  pval:  0.0


  1%|          | 2/300 [00:11<28:06,  5.66s/it]

R2: 0.09175332381306467  corr:  0.47038838518093745  pval:  0.0


  1%|          | 3/300 [00:17<28:09,  5.69s/it]

R2: 0.19413438034291186  corr:  0.5390674550252762  pval:  0.0


  1%|▏         | 4/300 [00:22<27:53,  5.65s/it]

R2: 0.34327647349355106  corr:  0.6353097884301397  pval:  0.0


  2%|▏         | 5/300 [00:28<27:53,  5.67s/it]

R2: 0.4354035786198074  corr:  0.6772832691860596  pval:  0.0


  2%|▏         | 6/300 [00:33<27:35,  5.63s/it]

R2: 0.5282413858019042  corr:  0.7362658328799299  pval:  0.0


  2%|▏         | 7/300 [00:39<27:46,  5.69s/it]

R2: 0.5672300547080573  corr:  0.7584238433838928  pval:  0.0


  3%|▎         | 8/300 [00:45<27:36,  5.67s/it]

R2: 0.5863956469800033  corr:  0.7695482408639674  pval:  0.0


  3%|▎         | 9/300 [00:51<27:33,  5.68s/it]

R2: 0.6097760947154143  corr:  0.783988680147546  pval:  0.0


  3%|▎         | 10/300 [00:56<27:40,  5.73s/it]

R2: 0.6180236137009492  corr:  0.7886218495915773  pval:  0.0


  4%|▎         | 11/300 [01:02<27:35,  5.73s/it]

R2: 0.6264697479728969  corr:  0.7924595623822611  pval:  0.0


  4%|▍         | 12/300 [01:08<27:14,  5.68s/it]

R2: 0.6382865902192848  corr:  0.8025302541595118  pval:  0.0


  4%|▍         | 13/300 [01:13<27:10,  5.68s/it]

R2: 0.6416297976751804  corr:  0.8064602447704213  pval:  0.0


  5%|▌         | 15/300 [01:24<25:48,  5.43s/it]

R2: 0.6468450180894842  corr:  0.8130617116949177  pval:  0.0


  5%|▌         | 16/300 [01:30<26:28,  5.59s/it]

R2: 0.6726189153695858  corr:  0.8242536525908832  pval:  0.0


  6%|▌         | 17/300 [01:35<26:09,  5.54s/it]

R2: 0.689177415129439  corr:  0.8301904566015673  pval:  0.0


  6%|▋         | 19/300 [01:45<25:23,  5.42s/it]

R2: 0.6996589510009805  corr:  0.8364656457696383  pval:  0.0


  7%|▋         | 20/300 [01:51<26:03,  5.58s/it]

R2: 0.7002037612406908  corr:  0.8367869044029072  pval:  0.0


  8%|▊         | 25/300 [02:16<23:45,  5.18s/it]

R2: 0.7009364694136284  corr:  0.8403918921234774  pval:  0.0


  9%|▊         | 26/300 [02:22<24:39,  5.40s/it]

R2: 0.7137645849111693  corr:  0.8452160989436708  pval:  0.0


  9%|▉         | 28/300 [02:32<24:11,  5.34s/it]

R2: 0.7246674087501896  corr:  0.8519800016611174  pval:  0.0


 10%|▉         | 29/300 [02:38<24:48,  5.49s/it]

R2: 0.7262288241468622  corr:  0.8524881892995386  pval:  0.0


 10%|█         | 30/300 [02:44<25:27,  5.66s/it]

R2: 0.7271263536362098  corr:  0.8528223157979735  pval:  0.0


 12%|█▏        | 37/300 [03:17<21:50,  4.98s/it]

R2: 0.7365927319083962  corr:  0.8592037334698681  pval:  0.0


 13%|█▎        | 38/300 [03:23<22:35,  5.17s/it]

R2: 0.7396311899478994  corr:  0.8608248063358216  pval:  0.0


 13%|█▎        | 39/300 [03:28<23:15,  5.35s/it]

R2: 0.7458794614114261  corr:  0.8639639797794753  pval:  0.0


 13%|█▎        | 40/300 [03:34<23:32,  5.43s/it]

R2: 0.746828222334756  corr:  0.8643585967877849  pval:  0.0


 16%|█▋        | 49/300 [04:14<19:50,  4.74s/it]

R2: 0.7562206969821372  corr:  0.8696390005287837  pval:  0.0


 19%|█▊        | 56/300 [04:47<19:55,  4.90s/it]

R2: 0.7629219517118383  corr:  0.8734611143962576  pval:  0.0


 26%|██▋       | 79/300 [06:34<18:14,  4.95s/it]

R2: 0.7640762831588783  corr:  0.8744349689741435  pval:  0.0


 29%|██▉       | 88/300 [07:17<17:38,  4.99s/it]

R2: 0.7655312256622423  corr:  0.8749676729338738  pval:  0.0


  0%|          | 1/300 [00:05<28:30,  5.72s/it]

R2: 0.011635844978259202  corr:  0.24302603113171425  pval:  0.0


  1%|          | 2/300 [00:11<28:56,  5.83s/it]

R2: 0.05585976749624344  corr:  0.34393663987735873  pval:  0.0


  1%|          | 3/300 [00:17<29:07,  5.89s/it]

R2: 0.13251019762904148  corr:  0.41390582320858454  pval:  0.0


  1%|▏         | 4/300 [00:23<28:58,  5.87s/it]

R2: 0.22711752116859807  corr:  0.4856811269356368  pval:  0.0


  2%|▏         | 5/300 [00:29<28:32,  5.81s/it]

R2: 0.3230539087470078  corr:  0.5705896472376205  pval:  0.0


  2%|▏         | 6/300 [00:34<28:24,  5.80s/it]

R2: 0.4281171763604953  corr:  0.6559230770996992  pval:  0.0


  2%|▏         | 7/300 [00:40<27:58,  5.73s/it]

R2: 0.4942860229672945  corr:  0.7033010975265263  pval:  0.0


  3%|▎         | 8/300 [00:46<27:47,  5.71s/it]

R2: 0.5513014396572651  corr:  0.742583981935417  pval:  0.0


  3%|▎         | 9/300 [00:51<27:26,  5.66s/it]

R2: 0.5728454870177613  corr:  0.7569191760664029  pval:  0.0


  3%|▎         | 10/300 [00:57<27:31,  5.70s/it]

R2: 0.5832468832261719  corr:  0.7637110680515392  pval:  0.0


  4%|▍         | 12/300 [01:07<26:21,  5.49s/it]

R2: 0.5915110140402253  corr:  0.7694330292612991  pval:  0.0


  4%|▍         | 13/300 [01:13<26:55,  5.63s/it]

R2: 0.6362372986213445  corr:  0.7978724344837914  pval:  0.0


  5%|▍         | 14/300 [01:19<27:10,  5.70s/it]

R2: 0.6500015316937129  corr:  0.8066264664324324  pval:  0.0


  5%|▌         | 15/300 [01:25<27:22,  5.76s/it]

R2: 0.6532515771666226  corr:  0.8108384404398644  pval:  0.0


  5%|▌         | 16/300 [01:31<27:31,  5.81s/it]

R2: 0.6653062259473381  corr:  0.8159218933568493  pval:  0.0


  6%|▌         | 18/300 [01:42<26:26,  5.63s/it]

R2: 0.6807559934788436  corr:  0.8257090238598916  pval:  0.0


  6%|▋         | 19/300 [01:48<26:34,  5.67s/it]

R2: 0.6825173960051945  corr:  0.8263649462262319  pval:  0.0


  7%|▋         | 20/300 [01:53<26:39,  5.71s/it]

R2: 0.685220911887412  corr:  0.8277809240364807  pval:  0.0


  9%|▊         | 26/300 [02:22<23:10,  5.07s/it]

R2: 0.7031755967350279  corr:  0.8395504195810238  pval:  0.0


  9%|▉         | 27/300 [02:28<23:51,  5.24s/it]

R2: 0.7045190730985775  corr:  0.8395367424909972  pval:  0.0


  9%|▉         | 28/300 [02:33<24:32,  5.41s/it]

R2: 0.7131078882314592  corr:  0.8447159332357229  pval:  0.0


 10%|▉         | 29/300 [02:39<24:57,  5.53s/it]

R2: 0.7138760238372195  corr:  0.8452555629380213  pval:  0.0


 10%|█         | 30/300 [02:45<25:07,  5.58s/it]

R2: 0.7151489197904148  corr:  0.845789354530645  pval:  0.0


 12%|█▏        | 35/300 [03:09<22:11,  5.02s/it]

R2: 0.7291005606980334  corr:  0.8544656510871789  pval:  0.0


 12%|█▏        | 37/300 [03:19<22:34,  5.15s/it]

R2: 0.7333105923501484  corr:  0.8568892780396461  pval:  0.0


 13%|█▎        | 38/300 [03:25<23:34,  5.40s/it]

R2: 0.7354671324922255  corr:  0.8579306621889708  pval:  0.0


 13%|█▎        | 39/300 [03:31<24:05,  5.54s/it]

R2: 0.7369553418991122  corr:  0.8586166447555863  pval:  0.0


 13%|█▎        | 40/300 [03:37<24:29,  5.65s/it]

R2: 0.7384451876588598  corr:  0.859408475089068  pval:  0.0


 15%|█▌        | 46/300 [04:06<21:27,  5.07s/it]

R2: 0.7391623960199141  corr:  0.8605845336908579  pval:  0.0


 16%|█▋        | 49/300 [04:20<21:06,  5.05s/it]

R2: 0.7408511134354046  corr:  0.8622789916142112  pval:  0.0


 17%|█▋        | 50/300 [04:26<21:53,  5.25s/it]

R2: 0.7475143847463867  corr:  0.8651279729763635  pval:  0.0


 19%|█▉        | 58/300 [05:04<20:15,  5.02s/it]

R2: 0.7516871120940576  corr:  0.8672668854411979  pval:  0.0


 20%|██        | 60/300 [05:14<20:31,  5.13s/it]

R2: 0.7531347058571809  corr:  0.8681059983625903  pval:  0.0


 23%|██▎       | 68/300 [05:52<19:07,  4.95s/it]

R2: 0.7564781226593124  corr:  0.8697933002842755  pval:  0.0


 23%|██▎       | 69/300 [05:58<19:46,  5.14s/it]

R2: 0.7596669525206323  corr:  0.8716862719137388  pval:  0.0


 26%|██▌       | 77/300 [06:36<19:07,  5.15s/it]

R2: 0.7598092029767519  corr:  0.8731799100122891  pval:  0.0


 27%|██▋       | 80/300 [06:51<18:38,  5.08s/it]

R2: 0.7603699905554389  corr:  0.8725926326534259  pval:  0.0


 30%|██▉       | 89/300 [07:33<17:14,  4.90s/it]

R2: 0.7661746940442633  corr:  0.8754134933997443  pval:  0.0


  0%|          | 1/300 [00:05<29:08,  5.85s/it]

R2: 0.007050503707723421  corr:  0.3347040289296928  pval:  0.0


  1%|          | 2/300 [00:11<28:36,  5.76s/it]

R2: 0.05733165545936847  corr:  0.4940752759694779  pval:  0.0


  1%|          | 3/300 [00:17<28:21,  5.73s/it]

R2: 0.17443985929899908  corr:  0.5463861855049934  pval:  0.0


  1%|▏         | 4/300 [00:22<28:09,  5.71s/it]

R2: 0.29384093156038105  corr:  0.5926852885040519  pval:  0.0


  2%|▏         | 5/300 [00:28<28:06,  5.72s/it]

R2: 0.43325166410960225  corr:  0.6758802563696068  pval:  0.0


  2%|▏         | 6/300 [00:34<27:55,  5.70s/it]

R2: 0.5308854373130647  corr:  0.7343780909216268  pval:  0.0


  2%|▏         | 7/300 [00:39<27:43,  5.68s/it]

R2: 0.5673140899472303  corr:  0.7540620784980879  pval:  0.0


  3%|▎         | 8/300 [00:45<27:49,  5.72s/it]

R2: 0.5962249283033089  corr:  0.7726588244862279  pval:  0.0


  3%|▎         | 9/300 [00:51<27:43,  5.72s/it]

R2: 0.6088076591120458  corr:  0.7829347132837237  pval:  0.0


  3%|▎         | 10/300 [00:57<27:40,  5.73s/it]

R2: 0.6205039945594826  corr:  0.7884914744774953  pval:  0.0


  4%|▎         | 11/300 [01:03<27:46,  5.77s/it]

R2: 0.6277134895469552  corr:  0.7970982001714411  pval:  0.0


  4%|▍         | 13/300 [01:13<26:20,  5.51s/it]

R2: 0.6562392708927524  corr:  0.8150967216554004  pval:  0.0


  5%|▍         | 14/300 [01:19<26:34,  5.57s/it]

R2: 0.663761405119937  corr:  0.820210089100235  pval:  0.0


  5%|▌         | 15/300 [01:25<27:03,  5.69s/it]

R2: 0.674620863295032  corr:  0.8238118091628276  pval:  0.0


  5%|▌         | 16/300 [01:31<27:26,  5.80s/it]

R2: 0.6918451489040273  corr:  0.8333703726265121  pval:  0.0


  6%|▌         | 18/300 [01:41<25:35,  5.45s/it]

R2: 0.7038473781783887  corr:  0.8395698947408597  pval:  0.0


  7%|▋         | 20/300 [01:51<25:21,  5.43s/it]

R2: 0.706252383809074  corr:  0.840472686678867  pval:  0.0


  9%|▉         | 27/300 [02:25<22:30,  4.95s/it]

R2: 0.722325615737601  corr:  0.8530181223874023  pval:  0.0


  9%|▉         | 28/300 [02:30<23:24,  5.16s/it]

R2: 0.7318655541319181  corr:  0.8561351401314737  pval:  0.0


 10%|▉         | 29/300 [02:36<24:09,  5.35s/it]

R2: 0.735070459740522  corr:  0.8574751591213801  pval:  0.0


 10%|█         | 30/300 [02:42<24:35,  5.46s/it]

R2: 0.7362498783786247  corr:  0.8581038050355233  pval:  0.0


 13%|█▎        | 38/300 [03:19<21:08,  4.84s/it]

R2: 0.7446831385264017  corr:  0.8637148578514041  pval:  0.0


 13%|█▎        | 40/300 [03:29<21:34,  4.98s/it]

R2: 0.7478426975474102  corr:  0.8650570603192292  pval:  0.0


 16%|█▋        | 49/300 [04:12<20:53,  4.99s/it]

R2: 0.7577789628055676  corr:  0.8707478926419193  pval:  0.0


 17%|█▋        | 50/300 [04:18<21:52,  5.25s/it]

R2: 0.7579523359307766  corr:  0.8706971761607237  pval:  0.0


 19%|█▉        | 58/300 [04:54<19:16,  4.78s/it]

R2: 0.7588111314687258  corr:  0.8713942828973706  pval:  0.0


 20%|█▉        | 59/300 [05:00<20:17,  5.05s/it]

R2: 0.7640868833918513  corr:  0.8743250113482783  pval:  0.0


 23%|██▎       | 70/300 [05:52<18:37,  4.86s/it]

R2: 0.7649279115118623  corr:  0.8747845854107862  pval:  0.0


  0%|          | 1/300 [00:06<30:12,  6.06s/it]

R2: 0.022802826556930333  corr:  0.4032130999246841  pval:  0.0


  1%|          | 2/300 [00:11<29:33,  5.95s/it]

R2: 0.09394201927180335  corr:  0.4491572396623116  pval:  0.0


  1%|          | 3/300 [00:17<29:18,  5.92s/it]

R2: 0.1502450249756363  corr:  0.43711246894234446  pval:  0.0


  1%|▏         | 4/300 [00:23<29:11,  5.92s/it]

R2: 0.18302839583723873  corr:  0.4354735182895715  pval:  0.0


  2%|▏         | 5/300 [00:29<28:48,  5.86s/it]

R2: 0.2320083346065388  corr:  0.4844315299718192  pval:  0.0


  2%|▏         | 6/300 [00:35<28:26,  5.81s/it]

R2: 0.3135883347362374  corr:  0.5643763905151417  pval:  0.0


  2%|▏         | 7/300 [00:40<28:04,  5.75s/it]

R2: 0.395136321958529  corr:  0.6325210632333073  pval:  0.0


  3%|▎         | 8/300 [00:46<28:04,  5.77s/it]

R2: 0.4606095106135316  corr:  0.6803826440668429  pval:  0.0


  3%|▎         | 9/300 [00:52<28:03,  5.79s/it]

R2: 0.5029406198924185  corr:  0.7107058658718718  pval:  0.0


  3%|▎         | 10/300 [00:58<27:43,  5.74s/it]

R2: 0.5202562639647282  corr:  0.7224594433322049  pval:  0.0


  4%|▎         | 11/300 [01:03<27:33,  5.72s/it]

R2: 0.5220473640260392  corr:  0.7331049964676223  pval:  0.0


  4%|▍         | 13/300 [01:13<26:06,  5.46s/it]

R2: 0.5967846951866781  corr:  0.7899739742107241  pval:  0.0


  5%|▍         | 14/300 [01:19<26:20,  5.53s/it]

R2: 0.6170814305898804  corr:  0.7955337351654065  pval:  0.0


  5%|▌         | 15/300 [01:25<26:38,  5.61s/it]

R2: 0.6261014329245336  corr:  0.8015465543656091  pval:  0.0


  5%|▌         | 16/300 [01:31<26:46,  5.66s/it]

R2: 0.646936048180097  corr:  0.8079928835555552  pval:  0.0


  6%|▌         | 18/300 [01:41<25:55,  5.52s/it]

R2: 0.6654612611900308  corr:  0.8166534667614409  pval:  0.0


  6%|▋         | 19/300 [01:47<26:17,  5.61s/it]

R2: 0.6738537637351805  corr:  0.8210533072577286  pval:  0.0


  7%|▋         | 20/300 [01:53<26:32,  5.69s/it]

R2: 0.676502739089481  corr:  0.8225177881509695  pval:  0.0


  8%|▊         | 23/300 [02:08<24:18,  5.27s/it]

R2: 0.6806722544980723  corr:  0.8267396070400215  pval:  0.0


  8%|▊         | 25/300 [02:19<24:45,  5.40s/it]

R2: 0.6994692657544077  corr:  0.8380955462920294  pval:  0.0


  9%|▊         | 26/300 [02:25<25:29,  5.58s/it]

R2: 0.7053941647125563  corr:  0.8405283618102071  pval:  0.0


  9%|▉         | 28/300 [02:35<24:51,  5.48s/it]

R2: 0.7157762071468043  corr:  0.846135791836071  pval:  0.0


 10%|▉         | 29/300 [02:41<25:21,  5.61s/it]

R2: 0.7214155443029009  corr:  0.8493707825305532  pval:  0.0


 10%|█         | 30/300 [02:47<25:34,  5.68s/it]

R2: 0.722208016292321  corr:  0.8498318424303184  pval:  0.0


 11%|█▏        | 34/300 [03:07<23:08,  5.22s/it]

R2: 0.7254404865514199  corr:  0.8518015651659667  pval:  0.0


 13%|█▎        | 39/300 [03:31<21:58,  5.05s/it]

R2: 0.7424032748028495  corr:  0.8620403931684345  pval:  0.0


 13%|█▎        | 40/300 [03:37<22:47,  5.26s/it]

R2: 0.7441451390206376  corr:  0.8628844610046186  pval:  0.0


 16%|█▌        | 48/300 [04:15<21:06,  5.02s/it]

R2: 0.7547945213320789  corr:  0.8697203089282511  pval:  0.0


 16%|█▋        | 49/300 [04:21<21:51,  5.23s/it]

R2: 0.7558674660749818  corr:  0.8695232264423295  pval:  0.0


 17%|█▋        | 50/300 [04:26<22:18,  5.35s/it]

R2: 0.7560934458558204  corr:  0.8696862945608433  pval:  0.0


 19%|█▉        | 58/300 [05:05<20:35,  5.10s/it]

R2: 0.7608808201148436  corr:  0.8723731178071499  pval:  0.0


 20%|██        | 60/300 [05:15<20:41,  5.17s/it]

R2: 0.7623319542067581  corr:  0.8732281174563739  pval:  0.0


 22%|██▏       | 67/300 [05:49<19:25,  5.00s/it]

R2: 0.7633611958156764  corr:  0.8740070545957205  pval:  0.0


 23%|██▎       | 69/300 [05:59<19:53,  5.16s/it]

R2: 0.7689707882290224  corr:  0.8769459106235235  pval:  0.0


 26%|██▌       | 78/300 [06:42<18:24,  4.98s/it]

R2: 0.7698187986045006  corr:  0.8774757699659907  pval:  0.0


 26%|██▋       | 79/300 [06:48<19:07,  5.19s/it]

R2: 0.7722672487112798  corr:  0.8791357599878667  pval:  0.0


 30%|██▉       | 89/300 [07:35<17:20,  4.93s/it]

R2: 0.7746427885020468  corr:  0.8803143011952198  pval:  0.0


100%|██████████| 300/300 [23:08<00:00,  4.63s/it]


R2 from the best models in each run are:
[0.7655253  0.76617748 0.76492614 0.77463616]
corr from the best models in each run are:
[0.87496319 0.87541521 0.87478422 0.88030991]
