Summary of outcomes:

div to ssh_cos only, batch_size=10
R2 from the best models in each run are:
[0.71200164 0.7092568  0.70846646 0.71314044]
corr from the best models in each run are:
[0.8454739  0.84274485 0.84231521 0.8457262 ]

vort to ssh_cos only, batch_size=10
R2 from the best models in each run are:
[0.83241847 0.82840353 0.82703668 0.82710327]
corr from the best models in each run are:
[0.91324089 0.91147217 0.91132234 0.91095138]

---------------------------------------------
div to ssh_cos and ssh_sin, batch_size=10
R2 from the best models in each run are:
[0.77560043 0.771282   0.77819786 0.7697045 ]
corr from the best models in each run are:
[0.88150735 0.88002645 0.8826575  0.87888121]


vort to ssh_cos and ssh_sin, batch_size=10
R2 from the best models in each run are:
[0.74091076 0.73678359 0.73939649 0.73511447]
corr from the best models in each run are:
[0.86151784 0.85899898 0.86089328 0.85819646]

---------------------------------------------
div to ssh_cos only, batch_size=100
R2 from the best models in each run are:
[0.70388961 0.69786856 0.70412668 0.69500771]
corr from the best models in each run are:
[0.84168713 0.83839298 0.84008428 0.83767132]

vort to ssh_cos only, batch_size=100
R2 from the best models in each run are:
[0.7655253  0.76617748 0.76492614 0.77463616]
corr from the best models in each run are:
[0.87496319 0.87541521 0.87478422 0.88030991]

---------------------------------------------

div to ssh_cos and ssh_sin, batch_size=100
R2 from the best models in each run are:
[0.76925564 0.76784907 0.7624617  0.76859775]
corr from the best models in each run are:
[0.87765357 0.87739345 0.87562212 0.87729587]


vort to ssh_cos and ssh_sin, batch_size=100
R2 from the best models in each run are:
[0.67702224 0.67874523 0.67075058 0.67682131]
corr from the best models in each run are:
[0.82337388 0.82430789 0.81952929 0.82334258]

In [1]:
#Previously I got weird results because my perforamnces from the vort and div run are the results of 
#Jeff's vort and div runs swapped. My run with (vort+div) is also slightly worse than Jeff's. Now I 
#try if I could reconstruct Jeff's results if I make the batch number to be 10 and make the output channel 
#to be ssh_cos, just like what Jeff did. 
#If these still don't agree with Jeff's results, then it is probably the batchnorm layer that's causing problems. 
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from netCDF4 import Dataset
from tqdm import tqdm
import torch.nn.functional as F
from sklearn.metrics import r2_score as R2
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score as r2
from copy import deepcopy
import utils
from unet import UNet_nobatchnorm
from scipy.stats import pearsonr
#JU's addtion to automate inputs and outputs
import helper_functions as hf
import os
def save_fn(var_input_list, var_output_list):
    var_input_join  = '_and_'.join(var_input_list)
    var_output_join = '_and_'.join(var_output_list)
    return '{}_to_{}'.format(var_input_join, var_output_join)
    
torch.cuda.set_device(1)
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
print ('Running on ', device)

Running on  cuda:1


In [2]:
torch.cuda.is_available()

True

In [3]:
print(torch.__version__)
print(torch.version.cuda)

2.5.1
12.6


In [4]:
maxEpochs =  300#small number is taken for debugging
nensemble = 4 #How many training sessions are run for each configuration ***
Nbase = 16

In [5]:
!nvidia-smi #GPU usage should be maxed out during training; tune batch_size according to that

Wed Apr  2 21:13:05 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:03:00.0 Off |                    0 |
| N/A   58C    P0            248W /  500W |   22493MiB /  81920MiB |     95%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [6]:
root_dir = '/work/uo0780/u241359/project_tide_synergy/data/'
nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

Ntrain = np.sum([nc.dimensions['time_counter'].size for nc in nctrains], axis = 0)
Ntest = np.sum([nc.dimensions['time_counter'].size for nc in nctest], axis = 0)

print('number of training records:', Ntrain)
print('number of testing records:', Ntest)

numTrainFiles = len(nctrains)
numRecsFile = nctrains[0].dimensions['time_counter'].size #How many snapshots in time in each data set there is
print (numRecsFile)

number of training records: 600
number of testing records: 150
150


In [7]:
def hwvorticity(u, v, dgrid = 4000):
    return (np.gradient(v, axis =2) - np.gradient(u, axis =1))/dgrid

def hwdivergence(u, v, dgrid = 4000):
    return (np.gradient(u, axis =2) + np.gradient(v, axis =1))/dgrid

def preload_data_vortdiv(nctrains, total_records):
    #total_records = Ntrain#sum(nc.dimensions['time_counter'].size for nc in nctrains)
    #dimensions of data of the nc file.
    max_height = 722
    max_width = 258
    all_input_data = np.zeros((total_records, N_inp, max_height, max_width))*np.nan
    all_output_data = np.zeros((total_records, N_out, max_height, max_width))*np.nan
    current_index = 0
    for ncindex, ncdata in enumerate(nctrains):
        num_recs = ncdata.dimensions['time_counter'].size #how many time stamps are there in each .nc file (i.e., at each turbulence level)
        rec_slice = slice(current_index, current_index + num_recs)
        for ind, var_name in enumerate(var_input_names):
            if var_name == 'vort':
                u = np.squeeze(ncdata.variables['u_xy_ins'])
                v = np.squeeze(ncdata.variables['v_xy_ins'])
                #u.shape: (150, 722, 257); v.shape: (150, 721, 258)
                #as u and v have different number of grid points in x and y, we truncate them so that their shapes agree, enabling the simple way to compute vorticities based on finite diff.
                data_slice = hwvorticity(u[:,:-1,:], v[:,:,:-1])
            elif var_name == 'div':
                u = np.squeeze(ncdata.variables['u_xy_ins'])
                v = np.squeeze(ncdata.variables['v_xy_ins'])
                data_slice = hwdivergence(u[:,:-1,:], v[:,:,:-1])
            else:           
                data_slice = np.squeeze(ncdata.variables[var_name])
            # print('data_slice shape:')
            # print(data_slice.shape)        
            #all_input_data[rec_slice, ind, :, :] = data_slice
            
            #For some variables, the dimensions in (x, y) may be smaller than (max_height, max_width). Changing the code so that it adapts them.
            # Get the actual dimensions of data_slice
            slice_height, slice_width = data_slice.shape[-2], data_slice.shape[-1]
            # Place data_slice into the corresponding slice of all_input_data
            all_input_data[rec_slice, ind, :slice_height, :slice_width] = data_slice
    

        for ind, var_name in enumerate(var_output_names):
            data_slice = np.squeeze(ncdata.variables[var_name])
            #all_output_data[rec_slice, ind, :, :] = data_slice
            # Get the actual dimensions of data_slice
            slice_height, slice_width = data_slice.shape[-2], data_slice.shape[-1]
            # Place data_slice into the corresponding slice of all_input_data
            all_output_data[rec_slice, ind, :slice_height, :slice_width] = data_slice

        current_index += num_recs
        
    return all_input_data, all_output_data
    


# Modify the loadtrain function to pull data from preloaded memory
def loaddata_preloaded_train(index, batch_size, all_input_data, all_output_data):
    rec_slice = slice(index, index + batch_size)
    lim = 720
    width = 256
    yslice = slice(0, lim)
    xslice = slice(0, width)
    # print('mean of squared values of loaded input data:')
    # print("{0:0.32f}".format(np.nanmean(all_input_data[rec_slice, :, yslice, xslice]**2)))
    return (all_input_data[rec_slice, :, yslice, xslice], 
            all_output_data[rec_slice, :, yslice, xslice])
#Load test data as one single batch
def loaddata_preloaded_test(all_input_data, all_output_data):
    #rec_slice = slice(index, index + batch_size)
    lim = 720
    width = 256
    yslice = slice(0, lim)
    xslice = slice(0, width)
    # print('rec_slice is:')
    # print(rec_slice)
    # print('mean of squared values of loaded input data:')
    # print("{0:0.32f}".format(np.nanmean(all_input_data[rec_slice, :, yslice, xslice]**2)))
    return (all_input_data[:, :, yslice, xslice], 
            all_output_data[:, :, yslice, xslice])



In [8]:
def run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all):
    ytest_slice = slice(0, 720)
    xtest_slice = slice(0, 256)
    rectest_slice = slice(0, 150)

    def totorch(x):
        return torch.tensor(x, dtype = torch.float).cuda()

    model = UNet_nobatchnorm(N_inp, N_out, bilinear = True, Nbase = Nbase).cuda()
    #model = torch.compile(UNet(N_inp, N_out, bilinear = True, Nbase = Nbase).cuda())

    if iensemble == 0:
        input = torch.randn(1,N_inp,256,720).to(device) 
        output = model(input)
        print('Model has ', utils.nparams(model)/1e6, ' million params')

    # for index in range(0, Ntrain, batch_size):
    #     inp, out = loadtrain_preloaded(index, batch_size, all_train_input, all_train_output)
    #     print(inp.shape, out.shape)
#         print(np.nanmean(inp**2), np.max(inp**2), inp.shape)
#         print(np.nanmean(out**2), np.max(out**2), inp.shape)

    inp_test, out_test = loaddata_preloaded_test(all_test_input, all_test_output)
    #inp, out_test = loadtest()
    # print('shapes of input and output TEST data:')
    # print(inp_test.shape, out_test.shape)
    with torch.no_grad():
        inp_test = totorch(inp_test)

    Tcycle = 10
    criterion_train  = nn.L1Loss()
    optim = torch.optim.AdamW(model.parameters(), lr=lr0, betas=(0.9, 0.999), eps=1e-8, weight_decay=1e-5*100) #increase weight_decay ***

    r2_test = np.zeros(maxEpochs)
    epochmin = []
    maxr2l = []

    learn = np.zeros(maxEpochs)
    minloss = 1000
    maxR2 = -1000
    minlosscount = 0
    perm = False

    model_best = deepcopy(model)  # Initialize before the loop for safety

    #print('Starting training loop')
    for epoch in tqdm(range(maxEpochs)):
        lr = utils.cosineSGDR(optim, epoch, T0=Tcycle, eta_min=0, eta_max=lr0, scheme = 'constant')  #captioning this seems to make the printed corr larger??***
        model.train()
        index_perm = np.arange(0, Ntrain, batch_size)
        
        if perm:
            index_perm = np.random.permutation(index_perm)
        
        for index in index_perm:
            inp, out = loaddata_preloaded_train(index, batch_size, all_train_input, all_train_output)            
#           inp, out = loadtrain(index, batch_size, nctrains)
            inp, out = totorch(inp), totorch(out)
            #continue #do this to pause the later operations to check how long it takes for the steps up to this 
            out_mod = model(inp)
            loss = criterion_train(out.squeeze(), out_mod.squeeze())
            #Set gradient to zero
            optim.zero_grad()
            #Compute gradients       
            loss.backward()
            #Update parameters with new gradient
            optim.step()
            #Record train loss
            #scheduler.step()
          
        model.eval()
        with torch.no_grad():
            #model_cpu = model.to('cpu')
            #out_mod = model_cpu(inp_test.to('cpu'))
            out_mod=model(inp_test)
            
            r2 = R2(out_test.flatten(), (out_mod).cpu().numpy().flatten())
            r2_test[epoch] = r2
            #print('Debugging: R2 of current epoch:', r2)#Debugging
            #record current best model and best predictions
            if maxR2 <  r2:
                maxR2 = r2
                epochmin.append(epoch)
                maxr2l.append(maxR2)                
                model_best = deepcopy(model)
                corr, pval = pearsonr(out_test.flatten(), (out_mod).cpu().numpy().flatten())
                print('R2:', r2, ' corr: ', corr, ' pval: ', pval)
            #model = model_cpu.to(device)

    #_, out_test = loadtest()
    model_best.eval()
    with torch.no_grad():
    #     inp_test = totorch(inp)
        model_best.to('cpu') #added by HW 
        out_mod = model_best(inp_test.to('cpu')).detach().cpu().numpy()

    R2_all[iensemble]=R2(out_test.flatten(), out_mod.flatten())
    corr_all[iensemble]=pearsonr(out_test.flatten(), out_mod.flatten())[0]
    # print('Best model R2:', R2_all[iensemble])#pearsonr(out_test.flatten(), out_mod.flatten())[0])
    # print('Best model corr:', corr_all[iensemble])#R2(out_test.flatten(), out_mod.flatten()))

    # Nx, Ny = out_test.shape[2:]; Nx, Ny

    # print(out_mod.shape, 'outout model shape')
    dr = '/work/uo0780/u241359/project_tide_synergy/trainedmodels' #'./models/to_vel'
    os.makedirs(dr, exist_ok=True) # exist_ok=True allows the function to do nothing (i.e., not raise an error) if the directory already exists.
    fstr = f'{save_fn_prefix}_rp_{iensemble}'
    PATH = dr + f'/{fstr}.pth'
    torch.save(model_best.state_dict(), PATH)

In [9]:
vi1 = 'div'

vo1 = 'ssh_cos'

save_fn_prefix  = 'any_{}_{}_smallbatch_cosonly_nobatchnorm'.format(vi1, vo1)
var_input_names = [vi1]
var_output_names = [vo1]

batch_size = 10 

N_inp = len(var_input_names)
N_out = len(var_output_names)

lr0 = 0.005*10/batch_size #Roughly should scale inversely to batch_size

#Recording performance metrics on test data after eaching training cycle
R2_all = np.zeros(nensemble)
corr_all = np.zeros(nensemble)

nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

all_train_input, all_train_output = preload_data_vortdiv(nctrains, Ntrain)
all_test_input, all_test_output = preload_data_vortdiv(nctest, Ntest)

#Normalize data
#Compute mean and variance for normalization
mean_input=np.nanmean(np.concatenate((all_train_input, all_test_input), axis=0),axis=(0, 2, 3))
mean_output=np.nanmean(np.concatenate((all_train_output, all_test_output), axis=0),axis=(0, 2, 3))
#Subtract the data with their means
all_train_input=all_train_input-mean_input[None, :, None, None]
all_train_output=all_train_output-mean_output[None, :, None, None]
all_test_input=all_test_input-mean_input[None, :, None, None]
all_test_output=all_test_output-mean_output[None, :, None, None]
#Compute the variances
var_input=np.nanmean((np.concatenate((all_train_input, all_test_input), axis=0))**2,axis=(0, 2, 3))
var_output=np.nanmean((np.concatenate((all_train_output, all_test_output), axis=0))**2,axis=(0, 2, 3))
print("mean and variance of all input data:")
print(mean_input,var_input)
print("mean and variance of all output data:")
print(mean_output,var_output)
#Scale the data so that they have variance of 1
all_train_input=all_train_input/np.sqrt(var_input[None, :, None, None])
all_train_output=all_train_output/np.sqrt(var_output[None, :, None, None])
all_test_input=all_test_input/np.sqrt(var_input[None, :, None, None])
all_test_output=all_test_output/np.sqrt(var_output[None, :, None, None])
#Have checked that after these operations, the data is scaled to be zero mean and variance 1.

for iensemble in np.arange(nensemble):
    run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all)  
print('R2 from the best models in each run are:')
print(R2_all)
print('corr from the best models in each run are:')
print(corr_all)

mean and variance of all input data:
[3.2595452e-09] [3.62891008e-11]
mean and variance of all output data:
[-0.00051623] [9.36516511e-05]
Model has  1.124401  million params


  0%|          | 1/300 [00:06<30:15,  6.07s/it]

R2: 0.4663811463231238  corr:  0.7132612632150401  pval:  0.0


  1%|          | 2/300 [00:11<29:12,  5.88s/it]

R2: 0.49390654730086836  corr:  0.7494709256339285  pval:  0.0


  1%|          | 3/300 [00:17<29:37,  5.99s/it]

R2: 0.6015499977612508  corr:  0.7878231325744074  pval:  0.0


  1%|▏         | 4/300 [00:24<30:24,  6.16s/it]

R2: 0.6226699702685096  corr:  0.79510323844323  pval:  0.0


  2%|▏         | 6/300 [00:38<32:43,  6.68s/it]

R2: 0.6352685911493035  corr:  0.8045640797614426  pval:  0.0


  2%|▏         | 7/300 [00:44<31:51,  6.53s/it]

R2: 0.6567035741708735  corr:  0.814255420401885  pval:  0.0


  3%|▎         | 8/300 [00:50<31:37,  6.50s/it]

R2: 0.6645318381304692  corr:  0.8173860610211466  pval:  0.0


  3%|▎         | 9/300 [00:57<31:19,  6.46s/it]

R2: 0.6722423583210043  corr:  0.8208430778003073  pval:  0.0


  6%|▌         | 17/300 [01:39<26:18,  5.58s/it]

R2: 0.6762045845765666  corr:  0.826371582765573  pval:  0.0


  6%|▌         | 18/300 [01:46<26:51,  5.71s/it]

R2: 0.6893654599745714  corr:  0.8319199913375251  pval:  0.0


  9%|▉         | 27/300 [02:32<23:36,  5.19s/it]

R2: 0.6951747263099897  corr:  0.8379303897762874  pval:  0.0


  9%|▉         | 28/300 [02:38<24:44,  5.46s/it]

R2: 0.7004151009904936  corr:  0.8388373312106567  pval:  0.0


 12%|█▏        | 37/300 [03:23<22:53,  5.22s/it]

R2: 0.7039101847375248  corr:  0.8421435797455943  pval:  0.0


 13%|█▎        | 38/300 [03:29<23:33,  5.40s/it]

R2: 0.7049896422213974  corr:  0.8418615834732635  pval:  0.0


 13%|█▎        | 39/300 [03:36<25:09,  5.78s/it]

R2: 0.7062890993171236  corr:  0.8412934105327283  pval:  0.0


 16%|█▌        | 47/300 [04:17<22:25,  5.32s/it]

R2: 0.7120020700480396  corr:  0.845473346416671  pval:  0.0


  0%|          | 1/300 [00:06<31:02,  6.23s/it]

R2: 0.4370642501647818  corr:  0.7073165373679062  pval:  0.0


  1%|          | 2/300 [00:12<31:54,  6.43s/it]

R2: 0.5882977887838265  corr:  0.7813765815668711  pval:  0.0


  1%|          | 3/300 [00:19<32:04,  6.48s/it]

R2: 0.6358098061064428  corr:  0.8013017184920861  pval:  0.0


  1%|▏         | 4/300 [00:26<33:39,  6.82s/it]

R2: 0.6460561899632197  corr:  0.8069143851389562  pval:  0.0


  2%|▏         | 6/300 [00:38<31:49,  6.50s/it]

R2: 0.649359411775863  corr:  0.8110075631622299  pval:  0.0


  2%|▏         | 7/300 [00:46<32:37,  6.68s/it]

R2: 0.658055259493677  corr:  0.8179840652585608  pval:  0.0


  3%|▎         | 8/300 [00:53<33:11,  6.82s/it]

R2: 0.6741442995554809  corr:  0.8234378887685825  pval:  0.0


  3%|▎         | 9/300 [00:59<32:31,  6.71s/it]

R2: 0.6756613887764142  corr:  0.8237398671729075  pval:  0.0


  6%|▌         | 17/300 [01:43<28:26,  6.03s/it]

R2: 0.6807714325645976  corr:  0.8309161475224451  pval:  0.0


  6%|▌         | 18/300 [01:51<30:25,  6.47s/it]

R2: 0.6922431003216591  corr:  0.8336494219279849  pval:  0.0


  9%|▉         | 27/300 [02:39<25:38,  5.64s/it]

R2: 0.701733352086263  corr:  0.8401030692656842  pval:  0.0


  9%|▉         | 28/300 [02:45<26:18,  5.80s/it]

R2: 0.7054223196628496  corr:  0.8405534783210693  pval:  0.0


 12%|█▏        | 37/300 [03:30<22:38,  5.17s/it]

R2: 0.706557851555108  corr:  0.8419282795889701  pval:  0.0


 13%|█▎        | 38/300 [03:36<23:31,  5.39s/it]

R2: 0.7092673464216106  corr:  0.8427510444798851  pval:  0.0


  0%|          | 1/300 [00:05<29:37,  5.94s/it]

R2: 0.5001273060989742  corr:  0.7319808437865019  pval:  0.0


  1%|          | 2/300 [00:12<30:24,  6.12s/it]

R2: 0.5747570231124117  corr:  0.7805845133574292  pval:  0.0


  1%|          | 3/300 [00:18<30:55,  6.25s/it]

R2: 0.6094464853946935  corr:  0.7859475958693537  pval:  0.0


  1%|▏         | 4/300 [00:25<32:17,  6.54s/it]

R2: 0.6352965740862375  corr:  0.8001840160276126  pval:  0.0


  2%|▏         | 5/300 [00:31<31:34,  6.42s/it]

R2: 0.654628992554741  corr:  0.8116647760689328  pval:  0.0


  2%|▏         | 6/300 [00:37<30:58,  6.32s/it]

R2: 0.6648618756277869  corr:  0.8189692964302094  pval:  0.0


  2%|▏         | 7/300 [00:43<30:09,  6.18s/it]

R2: 0.6683820251547147  corr:  0.8204949413790179  pval:  0.0


  3%|▎         | 8/300 [00:49<29:36,  6.08s/it]

R2: 0.6718604900080314  corr:  0.8202570506867514  pval:  0.0


  3%|▎         | 9/300 [00:57<31:48,  6.56s/it]

R2: 0.676396929505463  corr:  0.8233702636002009  pval:  0.0


  5%|▌         | 16/300 [01:31<24:34,  5.19s/it]

R2: 0.6858645116390626  corr:  0.830040227208357  pval:  0.0


  6%|▌         | 18/300 [01:43<26:09,  5.57s/it]

R2: 0.694077623353422  corr:  0.8338568293743011  pval:  0.0


  8%|▊         | 25/300 [02:18<24:01,  5.24s/it]

R2: 0.694147612242463  corr:  0.8336540833379121  pval:  0.0


  9%|▉         | 27/300 [02:31<27:55,  6.14s/it]

R2: 0.6952142552067062  corr:  0.8370888899220392  pval:  0.0


  9%|▉         | 28/300 [02:38<29:47,  6.57s/it]

R2: 0.7041676384150966  corr:  0.8398614230830528  pval:  0.0


 13%|█▎        | 38/300 [03:32<25:29,  5.84s/it]

R2: 0.7084663150734232  corr:  0.8423143417432972  pval:  0.0


  0%|          | 1/300 [00:06<34:41,  6.96s/it]

R2: 0.370039554897754  corr:  0.6981897902053559  pval:  0.0


  1%|          | 2/300 [00:13<33:29,  6.74s/it]

R2: 0.5467716708754473  corr:  0.7599568842746227  pval:  0.0


  1%|          | 3/300 [00:20<33:03,  6.68s/it]

R2: 0.6276866214928267  corr:  0.7925530830972265  pval:  0.0


  2%|▏         | 5/300 [00:31<30:12,  6.14s/it]

R2: 0.6497163651334952  corr:  0.809720404326807  pval:  0.0


  2%|▏         | 6/300 [00:38<31:48,  6.49s/it]

R2: 0.650683057963422  corr:  0.8106498610567608  pval:  0.0


  3%|▎         | 8/300 [00:52<32:07,  6.60s/it]

R2: 0.6680034890948361  corr:  0.8188686637445172  pval:  0.0


  3%|▎         | 9/300 [00:58<31:17,  6.45s/it]

R2: 0.6704910041000842  corr:  0.8206608978279224  pval:  0.0


  5%|▍         | 14/300 [01:23<25:41,  5.39s/it]

R2: 0.6715180801344658  corr:  0.8210795376707735  pval:  0.0


  5%|▌         | 16/300 [01:33<25:33,  5.40s/it]

R2: 0.6722524594192908  corr:  0.8222368217842784  pval:  0.0


  6%|▌         | 17/300 [01:39<26:10,  5.55s/it]

R2: 0.6735927463761084  corr:  0.8229405045249505  pval:  0.0


  6%|▌         | 18/300 [01:45<27:14,  5.79s/it]

R2: 0.6782947883948336  corr:  0.824820793691211  pval:  0.0


  6%|▋         | 19/300 [01:51<27:28,  5.87s/it]

R2: 0.6899768387765548  corr:  0.8317321573444445  pval:  0.0


  9%|▉         | 28/300 [02:36<23:35,  5.20s/it]

R2: 0.6970626574370601  corr:  0.8360081863318991  pval:  0.0


 10%|▉         | 29/300 [02:42<24:56,  5.52s/it]

R2: 0.707011929412241  corr:  0.8416403687206552  pval:  0.0


 13%|█▎        | 38/300 [03:29<23:55,  5.48s/it]

R2: 0.7121017565722534  corr:  0.8446821939041775  pval:  0.0


 13%|█▎        | 39/300 [03:35<24:49,  5.71s/it]

R2: 0.7131391989957544  corr:  0.8457262348076483  pval:  0.0


100%|██████████| 300/300 [25:04<00:00,  5.01s/it]


R2 from the best models in each run are:
[0.71200164 0.7092568  0.70846646 0.71314044]
corr from the best models in each run are:
[0.8454739  0.84274485 0.84231521 0.8457262 ]


In [10]:
vi1 = 'div'

vo1 = 'ssh_cos'
vo2 = 'ssh_sin'

save_fn_prefix  = 'any_{}_{}{}_smallbatch_nobatchnorm'.format(vi1, vo1, vo2)
var_input_names = [vi1]
var_output_names = [vo1, vo2]

batch_size = 10 

N_inp = len(var_input_names)
N_out = len(var_output_names)

lr0 = 0.005*10/batch_size #Roughly should scale inversely to batch_size

#Recording performance metrics on test data after eaching training cycle
R2_all = np.zeros(nensemble)
corr_all = np.zeros(nensemble)

nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

all_train_input, all_train_output = preload_data_vortdiv(nctrains, Ntrain)
all_test_input, all_test_output = preload_data_vortdiv(nctest, Ntest)

#Normalize data
#Compute mean and variance for normalization
mean_input=np.nanmean(np.concatenate((all_train_input, all_test_input), axis=0),axis=(0, 2, 3))
mean_output=np.nanmean(np.concatenate((all_train_output, all_test_output), axis=0),axis=(0, 2, 3))
#Subtract the data with their means
all_train_input=all_train_input-mean_input[None, :, None, None]
all_train_output=all_train_output-mean_output[None, :, None, None]
all_test_input=all_test_input-mean_input[None, :, None, None]
all_test_output=all_test_output-mean_output[None, :, None, None]
#Compute the variances
var_input=np.nanmean((np.concatenate((all_train_input, all_test_input), axis=0))**2,axis=(0, 2, 3))
var_output=np.nanmean((np.concatenate((all_train_output, all_test_output), axis=0))**2,axis=(0, 2, 3))
print("mean and variance of all input data:")
print(mean_input,var_input)
print("mean and variance of all output data:")
print(mean_output,var_output)
#Scale the data so that they have variance of 1
all_train_input=all_train_input/np.sqrt(var_input[None, :, None, None])
all_train_output=all_train_output/np.sqrt(var_output[None, :, None, None])
all_test_input=all_test_input/np.sqrt(var_input[None, :, None, None])
all_test_output=all_test_output/np.sqrt(var_output[None, :, None, None])
#Have checked that after these operations, the data is scaled to be zero mean and variance 1.

for iensemble in np.arange(nensemble):
    run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all)  
print('R2 from the best models in each run are:')
print(R2_all)
print('corr from the best models in each run are:')
print(corr_all)

mean and variance of all input data:
[3.2595452e-09] [3.62891008e-11]
mean and variance of all output data:
[-5.16228102e-04 -9.83592627e-05] [9.36516511e-05 1.01456128e-04]
Model has  1.124418  million params


  0%|          | 1/300 [00:09<46:33,  9.34s/it]

R2: 0.039152575088112984  corr:  0.7135761386136017  pval:  0.0


  1%|          | 2/300 [00:18<46:47,  9.42s/it]

R2: 0.6448040315219005  corr:  0.8087175468879996  pval:  0.0


  1%|          | 3/300 [00:27<44:12,  8.93s/it]

R2: 0.6848474621824734  corr:  0.8310567974927644  pval:  0.0


  1%|▏         | 4/300 [00:35<43:14,  8.76s/it]

R2: 0.6849200641842135  corr:  0.8337419706235015  pval:  0.0


  2%|▏         | 5/300 [00:44<42:19,  8.61s/it]

R2: 0.6973529537254259  corr:  0.8410562509465997  pval:  0.0


  2%|▏         | 6/300 [00:52<42:21,  8.65s/it]

R2: 0.7144835976633963  corr:  0.8511048475001027  pval:  0.0


  2%|▏         | 7/300 [01:01<42:29,  8.70s/it]

R2: 0.7203809814138824  corr:  0.8564773337446346  pval:  0.0


  3%|▎         | 8/300 [01:11<44:04,  9.06s/it]

R2: 0.7336195649696161  corr:  0.8610998562301168  pval:  0.0


  3%|▎         | 9/300 [01:19<42:25,  8.75s/it]

R2: 0.7434305375522665  corr:  0.8643474005141082  pval:  0.0


  3%|▎         | 10/300 [01:27<40:58,  8.48s/it]

R2: 0.7464497820651101  corr:  0.8648182039579426  pval:  0.0


  6%|▌         | 17/300 [02:06<29:14,  6.20s/it]

R2: 0.7548983308904392  corr:  0.8702782317395533  pval:  0.0


  6%|▋         | 19/300 [02:19<29:52,  6.38s/it]

R2: 0.7587289626596432  corr:  0.8724217603190769  pval:  0.0


  7%|▋         | 20/300 [02:28<34:40,  7.43s/it]

R2: 0.7592986152490417  corr:  0.872011766772178  pval:  0.0


  9%|▉         | 27/300 [03:14<32:16,  7.09s/it]

R2: 0.760099936395435  corr:  0.8734117664168269  pval:  0.0


  9%|▉         | 28/300 [03:23<34:15,  7.56s/it]

R2: 0.7615530494441134  corr:  0.8745761751405551  pval:  0.0


 10%|▉         | 29/300 [03:33<37:13,  8.24s/it]

R2: 0.7680231407396118  corr:  0.8772391953317481  pval:  0.0


 13%|█▎        | 39/300 [04:37<31:54,  7.34s/it]

R2: 0.7739086780416167  corr:  0.8805422732569279  pval:  0.0


 16%|█▋        | 49/300 [05:40<27:55,  6.68s/it]

R2: 0.7756006867256608  corr:  0.8815072748956033  pval:  0.0


  0%|          | 1/300 [00:07<37:48,  7.59s/it]

R2: 0.36312538377336656  corr:  0.7383943443337425  pval:  0.0


  1%|          | 2/300 [00:15<37:26,  7.54s/it]

R2: 0.620667116679115  corr:  0.7954631808721521  pval:  0.0


  1%|          | 3/300 [00:22<37:42,  7.62s/it]

R2: 0.7007961865482729  corr:  0.8383463276985309  pval:  0.0


  1%|▏         | 4/300 [00:32<41:09,  8.34s/it]

R2: 0.7132920293697829  corr:  0.8466507497361567  pval:  0.0


  2%|▏         | 5/300 [00:40<41:10,  8.38s/it]

R2: 0.714729167737218  corr:  0.8498729568814279  pval:  0.0


  2%|▏         | 7/300 [00:55<39:40,  8.12s/it]

R2: 0.7279837684365431  corr:  0.8547107067128841  pval:  0.0


  3%|▎         | 8/300 [01:04<40:37,  8.35s/it]

R2: 0.7354488259098901  corr:  0.8598647226588391  pval:  0.0


  3%|▎         | 9/300 [01:13<40:48,  8.41s/it]

R2: 0.740609481728641  corr:  0.8625125224150157  pval:  0.0


  6%|▌         | 17/300 [02:13<38:10,  8.09s/it]

R2: 0.7448003212554581  corr:  0.8664228966155363  pval:  0.0


  6%|▌         | 18/300 [02:21<38:23,  8.17s/it]

R2: 0.7512269594460921  corr:  0.8694241964373134  pval:  0.0


  6%|▋         | 19/300 [02:30<38:42,  8.26s/it]

R2: 0.7529060103746301  corr:  0.8696280272809154  pval:  0.0


  7%|▋         | 20/300 [02:37<37:42,  8.08s/it]

R2: 0.753480221543328  corr:  0.868913810355598  pval:  0.0


  9%|▉         | 28/300 [03:32<32:41,  7.21s/it]

R2: 0.7585296577838838  corr:  0.873283574385953  pval:  0.0


 10%|▉         | 29/300 [03:40<34:00,  7.53s/it]

R2: 0.7609675635125304  corr:  0.8741292968120236  pval:  0.0


 10%|█         | 30/300 [03:48<34:48,  7.74s/it]

R2: 0.7613787590490944  corr:  0.8734999692310256  pval:  0.0


 13%|█▎        | 38/300 [04:39<28:30,  6.53s/it]

R2: 0.7679101378734382  corr:  0.8781073584475348  pval:  0.0


 16%|█▌        | 48/300 [05:38<27:25,  6.53s/it]

R2: 0.7712835888483411  corr:  0.8800272512836562  pval:  0.0


  0%|          | 1/300 [00:07<39:38,  7.96s/it]

R2: 0.5160855391118806  corr:  0.7774272624269721  pval:  0.0


  1%|          | 2/300 [00:16<41:35,  8.37s/it]

R2: 0.6188898008192667  corr:  0.8149561049015661  pval:  0.0


  1%|          | 3/300 [00:24<40:09,  8.11s/it]

R2: 0.6980127335030244  corr:  0.8393376048710924  pval:  0.0


  1%|▏         | 4/300 [00:31<38:34,  7.82s/it]

R2: 0.724002494061913  corr:  0.8526166317736793  pval:  0.0


  2%|▏         | 5/300 [00:40<39:42,  8.08s/it]

R2: 0.7247905128159093  corr:  0.851641706679322  pval:  0.0


  2%|▏         | 6/300 [00:48<39:50,  8.13s/it]

R2: 0.7310455502592756  corr:  0.8570721791626851  pval:  0.0


  3%|▎         | 8/300 [01:03<39:04,  8.03s/it]

R2: 0.7428221467198464  corr:  0.8637418833799791  pval:  0.0


  6%|▌         | 18/300 [02:02<31:02,  6.61s/it]

R2: 0.7528984346904055  corr:  0.8702850355876148  pval:  0.0


  7%|▋         | 20/300 [02:16<32:33,  6.98s/it]

R2: 0.7556953006507434  corr:  0.8708742250145699  pval:  0.0


  9%|▉         | 27/300 [03:07<35:58,  7.91s/it]

R2: 0.7637988305466139  corr:  0.8758970223577908  pval:  0.0


  9%|▉         | 28/300 [03:16<36:45,  8.11s/it]

R2: 0.7698332163648298  corr:  0.8782087971234565  pval:  0.0


 12%|█▏        | 37/300 [04:09<28:47,  6.57s/it]

R2: 0.7714776998985988  corr:  0.8800364502250047  pval:  0.0


 13%|█▎        | 38/300 [04:19<32:10,  7.37s/it]

R2: 0.7774746100688785  corr:  0.8821505590365281  pval:  0.0


 16%|█▌        | 48/300 [05:24<31:08,  7.41s/it]

R2: 0.7782030681099804  corr:  0.882660365405339  pval:  0.0


  0%|          | 1/300 [00:08<41:21,  8.30s/it]

R2: 0.5725109893953588  corr:  0.7976499341916825  pval:  0.0


  1%|          | 2/300 [00:17<42:55,  8.64s/it]

R2: 0.6938532079778605  corr:  0.8346851556693601  pval:  0.0


  1%|          | 3/300 [00:25<41:58,  8.48s/it]

R2: 0.6978749551980864  corr:  0.8361492967905255  pval:  0.0


  1%|▏         | 4/300 [00:33<41:46,  8.47s/it]

R2: 0.7141641102375191  corr:  0.8476574983017323  pval:  0.0


  2%|▏         | 7/300 [00:53<35:21,  7.24s/it]

R2: 0.7267574725473657  corr:  0.8542170194277182  pval:  0.0


  3%|▎         | 8/300 [01:01<36:24,  7.48s/it]

R2: 0.7378054197637403  corr:  0.8601345029373357  pval:  0.0


  3%|▎         | 9/300 [01:10<38:16,  7.89s/it]

R2: 0.7416937108867074  corr:  0.8623984158242048  pval:  0.0


  5%|▌         | 15/300 [01:49<33:37,  7.08s/it]

R2: 0.7439887661667339  corr:  0.8654032190941257  pval:  0.0


  6%|▌         | 17/300 [02:02<33:30,  7.10s/it]

R2: 0.7457921280212788  corr:  0.8659101473920154  pval:  0.0


  6%|▌         | 18/300 [02:11<35:15,  7.50s/it]

R2: 0.7463970315027696  corr:  0.8657776297535814  pval:  0.0


  6%|▋         | 19/300 [02:20<37:34,  8.02s/it]

R2: 0.7493121365650719  corr:  0.8678665046418381  pval:  0.0


  7%|▋         | 20/300 [02:29<39:12,  8.40s/it]

R2: 0.7526815702609904  corr:  0.8690564410367245  pval:  0.0


  9%|▉         | 28/300 [03:20<30:40,  6.77s/it]

R2: 0.7577645529951922  corr:  0.8722443802385972  pval:  0.0


 10%|▉         | 29/300 [03:28<32:45,  7.25s/it]

R2: 0.7625375981590036  corr:  0.8747212654340557  pval:  0.0


 13%|█▎        | 38/300 [04:26<31:03,  7.11s/it]

R2: 0.7674581870654364  corr:  0.8770360863642495  pval:  0.0


 13%|█▎        | 39/300 [04:35<32:57,  7.58s/it]

R2: 0.7690721391740467  corr:  0.8782538890648184  pval:  0.0


 17%|█▋        | 50/300 [05:43<28:51,  6.93s/it]

R2: 0.7697191687263948  corr:  0.878884545698211  pval:  0.0


100%|██████████| 300/300 [30:14<00:00,  6.05s/it]


R2 from the best models in each run are:
[0.77560043 0.771282   0.77819786 0.7697045 ]
corr from the best models in each run are:
[0.88150735 0.88002645 0.8826575  0.87888121]


In [11]:
vi1 = 'div'

vo1 = 'ssh_cos'
vo2 = 'ssh_sin'

save_fn_prefix  = 'any_{}_{}{}_nobatchnorm'.format(vi1, vo1, vo2)
var_input_names = [vi1]
var_output_names = [vo1, vo2]

batch_size = 100

N_inp = len(var_input_names)
N_out = len(var_output_names)

lr0 = 0.005*10/batch_size #Roughly should scale inversely to batch_size

#Recording performance metrics on test data after eaching training cycle
R2_all = np.zeros(nensemble)
corr_all = np.zeros(nensemble)

nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

all_train_input, all_train_output = preload_data_vortdiv(nctrains, Ntrain)
all_test_input, all_test_output = preload_data_vortdiv(nctest, Ntest)

#Normalize data
#Compute mean and variance for normalization
mean_input=np.nanmean(np.concatenate((all_train_input, all_test_input), axis=0),axis=(0, 2, 3))
mean_output=np.nanmean(np.concatenate((all_train_output, all_test_output), axis=0),axis=(0, 2, 3))
#Subtract the data with their means
all_train_input=all_train_input-mean_input[None, :, None, None]
all_train_output=all_train_output-mean_output[None, :, None, None]
all_test_input=all_test_input-mean_input[None, :, None, None]
all_test_output=all_test_output-mean_output[None, :, None, None]
#Compute the variances
var_input=np.nanmean((np.concatenate((all_train_input, all_test_input), axis=0))**2,axis=(0, 2, 3))
var_output=np.nanmean((np.concatenate((all_train_output, all_test_output), axis=0))**2,axis=(0, 2, 3))
print("mean and variance of all input data:")
print(mean_input,var_input)
print("mean and variance of all output data:")
print(mean_output,var_output)
#Scale the data so that they have variance of 1
all_train_input=all_train_input/np.sqrt(var_input[None, :, None, None])
all_train_output=all_train_output/np.sqrt(var_output[None, :, None, None])
all_test_input=all_test_input/np.sqrt(var_input[None, :, None, None])
all_test_output=all_test_output/np.sqrt(var_output[None, :, None, None])
#Have checked that after these operations, the data is scaled to be zero mean and variance 1.

for iensemble in np.arange(nensemble):
    run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all)  
print('R2 from the best models in each run are:')
print(R2_all)
print('corr from the best models in each run are:')
print(corr_all)

mean and variance of all input data:
[3.2595452e-09] [3.62891008e-11]
mean and variance of all output data:
[-5.16228102e-04 -9.83592627e-05] [9.36516511e-05 1.01456128e-04]
Model has  1.124418  million params


  0%|          | 1/300 [00:08<42:20,  8.50s/it]

R2: 0.009642860031619849  corr:  0.10471265168434726  pval:  0.0


  1%|          | 2/300 [00:16<40:10,  8.09s/it]

R2: 0.07112478071079265  corr:  0.46183758598794933  pval:  0.0


  1%|          | 3/300 [00:24<41:17,  8.34s/it]

R2: 0.2008733456051076  corr:  0.5949714362185329  pval:  0.0


  1%|▏         | 4/300 [00:32<40:07,  8.13s/it]

R2: 0.3921476772415634  corr:  0.7054040780396111  pval:  0.0


  2%|▏         | 5/300 [00:42<42:22,  8.62s/it]

R2: 0.522033934762892  corr:  0.7552387207317607  pval:  0.0


  2%|▏         | 6/300 [00:50<41:16,  8.42s/it]

R2: 0.5791461511558247  corr:  0.7788704644734072  pval:  0.0


  2%|▏         | 7/300 [01:00<43:27,  8.90s/it]

R2: 0.5970661632313012  corr:  0.7897705792387438  pval:  0.0


  3%|▎         | 8/300 [01:09<43:37,  8.97s/it]

R2: 0.6043604802074333  corr:  0.791161315106524  pval:  0.0


  3%|▎         | 9/300 [01:17<42:26,  8.75s/it]

R2: 0.6054309190131506  corr:  0.7916696024739326  pval:  0.0


  3%|▎         | 10/300 [01:25<41:33,  8.60s/it]

R2: 0.6064639926282969  corr:  0.7921031911816365  pval:  0.0


  4%|▍         | 12/300 [01:38<36:36,  7.63s/it]

R2: 0.6300090180839831  corr:  0.7970985016104216  pval:  0.0


  4%|▍         | 13/300 [01:46<36:09,  7.56s/it]

R2: 0.6511901639747261  corr:  0.8122893240247349  pval:  0.0


  5%|▍         | 14/300 [01:53<35:51,  7.52s/it]

R2: 0.6698673684239418  corr:  0.8202932553600146  pval:  0.0


  6%|▌         | 17/300 [02:11<31:45,  6.73s/it]

R2: 0.675627546579866  corr:  0.8259147213268351  pval:  0.0


  6%|▋         | 19/300 [02:24<31:45,  6.78s/it]

R2: 0.678011712773527  corr:  0.8278238773287463  pval:  0.0


  7%|▋         | 20/300 [02:32<33:04,  7.09s/it]

R2: 0.6789434844848152  corr:  0.8283190631888979  pval:  0.0


  7%|▋         | 21/300 [02:40<33:54,  7.29s/it]

R2: 0.6865904805094243  corr:  0.8322979325850377  pval:  0.0


  7%|▋         | 22/300 [02:48<34:27,  7.44s/it]

R2: 0.6912683746582824  corr:  0.838186351164941  pval:  0.0


  8%|▊         | 23/300 [02:55<34:39,  7.51s/it]

R2: 0.7101548583767103  corr:  0.8460355347980627  pval:  0.0


  8%|▊         | 24/300 [03:03<34:57,  7.60s/it]

R2: 0.7150554509384963  corr:  0.8462685909712281  pval:  0.0


  9%|▊         | 26/300 [03:16<32:45,  7.18s/it]

R2: 0.7167878121471085  corr:  0.8480701833800074  pval:  0.0


  9%|▉         | 28/300 [03:29<31:15,  6.89s/it]

R2: 0.7176454403819232  corr:  0.8476507904647189  pval:  0.0


 10%|█         | 30/300 [03:43<30:55,  6.87s/it]

R2: 0.7224941029396182  corr:  0.8509853328840379  pval:  0.0


 12%|█▏        | 35/300 [04:11<27:43,  6.28s/it]

R2: 0.7323136162166586  corr:  0.8585394652736722  pval:  0.0


 12%|█▏        | 36/300 [04:19<29:43,  6.75s/it]

R2: 0.7358188167916506  corr:  0.8582826601616098  pval:  0.0


 13%|█▎        | 38/300 [04:32<29:11,  6.69s/it]

R2: 0.7377489175426133  corr:  0.8593746929147831  pval:  0.0


 13%|█▎        | 39/300 [04:39<30:02,  6.90s/it]

R2: 0.7390279562855433  corr:  0.8598343314620789  pval:  0.0


 13%|█▎        | 40/300 [04:47<30:37,  7.07s/it]

R2: 0.7427367049428758  corr:  0.8619113487844636  pval:  0.0


 16%|█▋        | 49/300 [05:37<25:36,  6.12s/it]

R2: 0.7435579521425322  corr:  0.863169013195184  pval:  0.0


 17%|█▋        | 50/300 [05:45<27:32,  6.61s/it]

R2: 0.7446085157630549  corr:  0.8636377284915028  pval:  0.0


 19%|█▉        | 57/300 [06:26<25:59,  6.42s/it]

R2: 0.7446427865511942  corr:  0.8656533707938432  pval:  0.0


 19%|█▉        | 58/300 [06:34<27:37,  6.85s/it]

R2: 0.7498705992086117  corr:  0.867023106829932  pval:  0.0


 20%|█▉        | 59/300 [06:42<28:39,  7.14s/it]

R2: 0.7536501599818682  corr:  0.8690580066508335  pval:  0.0


 23%|██▎       | 69/300 [07:36<22:27,  5.84s/it]

R2: 0.7639591086630207  corr:  0.8746593766523263  pval:  0.0


 26%|██▋       | 79/300 [08:32<22:28,  6.10s/it]

R2: 0.7654341390199408  corr:  0.8760406220667744  pval:  0.0


 29%|██▉       | 88/300 [09:23<21:53,  6.19s/it]

R2: 0.7692535735080415  corr:  0.8776530101591796  pval:  0.0


  0%|          | 1/300 [00:07<37:06,  7.44s/it]

R2: -0.000983134475142533  corr:  0.1116522251555548  pval:  0.0


  1%|          | 2/300 [00:15<38:10,  7.69s/it]

R2: 0.0856538802335165  corr:  0.32163764753786556  pval:  0.0


  1%|          | 3/300 [00:23<38:25,  7.76s/it]

R2: 0.19659274857834985  corr:  0.47827747130875975  pval:  0.0


  1%|▏         | 4/300 [00:31<38:47,  7.86s/it]

R2: 0.34881629009455284  corr:  0.6172226692476714  pval:  0.0


  2%|▏         | 5/300 [00:39<39:04,  7.95s/it]

R2: 0.46654707470433654  corr:  0.6924955528738498  pval:  0.0


  2%|▏         | 6/300 [00:47<39:28,  8.06s/it]

R2: 0.5314975251500922  corr:  0.7397437899051875  pval:  0.0


  2%|▏         | 7/300 [00:55<39:32,  8.10s/it]

R2: 0.5777316581541994  corr:  0.7695740483772381  pval:  0.0


  3%|▎         | 8/300 [01:03<38:42,  7.96s/it]

R2: 0.604171652123598  corr:  0.7853851503796787  pval:  0.0


  3%|▎         | 9/300 [01:10<37:59,  7.83s/it]

R2: 0.614841167997579  corr:  0.7894989788523928  pval:  0.0


  3%|▎         | 10/300 [01:18<36:58,  7.65s/it]

R2: 0.6208062879792089  corr:  0.791628689874481  pval:  0.0


  4%|▎         | 11/300 [01:25<36:52,  7.65s/it]

R2: 0.6301635247221671  corr:  0.7960823557341393  pval:  0.0


  4%|▍         | 12/300 [01:33<37:12,  7.75s/it]

R2: 0.6684416013182639  corr:  0.8181419562084831  pval:  0.0


  5%|▍         | 14/300 [01:49<38:31,  8.08s/it]

R2: 0.6903341627070718  corr:  0.8339963858670039  pval:  0.0


  5%|▌         | 15/300 [01:57<38:13,  8.05s/it]

R2: 0.7002526619870264  corr:  0.8410312703877029  pval:  0.0


  6%|▌         | 17/300 [02:10<34:56,  7.41s/it]

R2: 0.7129820590865079  corr:  0.8452961890163362  pval:  0.0


  6%|▋         | 19/300 [02:24<33:31,  7.16s/it]

R2: 0.7163339720942694  corr:  0.8465522601805616  pval:  0.0


  7%|▋         | 20/300 [02:32<34:21,  7.36s/it]

R2: 0.7179913047617354  corr:  0.8474870855713894  pval:  0.0


  8%|▊         | 24/300 [02:55<29:30,  6.42s/it]

R2: 0.7208369447709915  corr:  0.8517263579739329  pval:  0.0


  9%|▉         | 28/300 [03:19<28:32,  6.30s/it]

R2: 0.7286830911625649  corr:  0.8554894063046228  pval:  0.0


 10%|▉         | 29/300 [03:26<30:05,  6.66s/it]

R2: 0.7296691157791846  corr:  0.8555891623978789  pval:  0.0


 10%|█         | 30/300 [03:34<31:22,  6.97s/it]

R2: 0.7304027166199917  corr:  0.855854533374217  pval:  0.0


 10%|█         | 31/300 [03:42<32:12,  7.18s/it]

R2: 0.7305505739871584  corr:  0.8551477190711881  pval:  0.0


 12%|█▏        | 36/300 [04:11<28:12,  6.41s/it]

R2: 0.7378026714982262  corr:  0.8609363615410871  pval:  0.0


 13%|█▎        | 38/300 [04:23<28:07,  6.44s/it]

R2: 0.7422722864191729  corr:  0.8629275993185752  pval:  0.0


 19%|█▉        | 57/300 [06:09<24:56,  6.16s/it]

R2: 0.7492664932740571  corr:  0.8667375501005986  pval:  0.0


 20%|█▉        | 59/300 [06:23<26:59,  6.72s/it]

R2: 0.7498186120063645  corr:  0.8672855510662535  pval:  0.0


 22%|██▏       | 67/300 [07:08<23:51,  6.15s/it]

R2: 0.7538835311263196  corr:  0.8696074393287807  pval:  0.0


 23%|██▎       | 68/300 [07:17<26:19,  6.81s/it]

R2: 0.7569513166511204  corr:  0.8717781555937635  pval:  0.0


 26%|██▋       | 79/300 [08:20<23:26,  6.36s/it]

R2: 0.7610872820002397  corr:  0.8738353348122638  pval:  0.0


 31%|███       | 92/300 [09:33<21:16,  6.14s/it]

R2: 0.7678470882204519  corr:  0.8773936053086853  pval:  0.0


  0%|          | 1/300 [00:07<37:37,  7.55s/it]

R2: -0.00854038038424898  corr:  0.0742689249169513  pval:  0.0


  1%|          | 2/300 [00:15<38:01,  7.66s/it]

R2: 0.05302565943472337  corr:  0.2398759971064615  pval:  0.0


  1%|          | 3/300 [00:23<38:51,  7.85s/it]

R2: 0.1803040433396289  corr:  0.48501570208021266  pval:  0.0


  1%|▏         | 4/300 [00:31<38:24,  7.78s/it]

R2: 0.4357511213969666  corr:  0.7324245819601491  pval:  0.0


  2%|▏         | 5/300 [00:39<38:43,  7.88s/it]

R2: 0.5609980836387971  corr:  0.7788516527105691  pval:  0.0


  2%|▏         | 6/300 [00:46<38:33,  7.87s/it]

R2: 0.634361494367615  corr:  0.8081592191245182  pval:  0.0


  2%|▏         | 7/300 [00:54<38:04,  7.80s/it]

R2: 0.6456909187819936  corr:  0.8147452199608666  pval:  0.0


  3%|▎         | 8/300 [01:02<38:02,  7.82s/it]

R2: 0.6578674784327052  corr:  0.8168924753324003  pval:  0.0


  3%|▎         | 9/300 [01:10<38:04,  7.85s/it]

R2: 0.6600146858294922  corr:  0.8180908098774397  pval:  0.0


  3%|▎         | 10/300 [01:18<37:52,  7.84s/it]

R2: 0.6634617546997441  corr:  0.8193287831040211  pval:  0.0


  4%|▍         | 12/300 [01:31<35:05,  7.31s/it]

R2: 0.6896742702788563  corr:  0.8324868808941477  pval:  0.0


  5%|▍         | 14/300 [01:44<33:30,  7.03s/it]

R2: 0.6995985296152218  corr:  0.8399470285614499  pval:  0.0


  5%|▌         | 15/300 [01:52<35:07,  7.40s/it]

R2: 0.701367421280007  corr:  0.8451885563404059  pval:  0.0


  6%|▌         | 17/300 [02:08<36:29,  7.74s/it]

R2: 0.7095128261647821  corr:  0.8436320700048597  pval:  0.0


  6%|▌         | 18/300 [02:16<37:15,  7.93s/it]

R2: 0.7180255821320684  corr:  0.8487423805558126  pval:  0.0


  6%|▋         | 19/300 [02:25<37:44,  8.06s/it]

R2: 0.7193868902911725  corr:  0.8482829079655922  pval:  0.0


  7%|▋         | 20/300 [02:33<37:52,  8.12s/it]

R2: 0.7200143014850473  corr:  0.8485646138767193  pval:  0.0


  8%|▊         | 25/300 [03:02<29:49,  6.51s/it]

R2: 0.7308107537851138  corr:  0.8555442212912829  pval:  0.0


 11%|█         | 33/300 [03:47<26:40,  5.99s/it]

R2: 0.7352231438803674  corr:  0.8590118580274277  pval:  0.0


 13%|█▎        | 38/300 [04:15<25:59,  5.95s/it]

R2: 0.7374582385864651  corr:  0.8631905043306699  pval:  0.0


 13%|█▎        | 39/300 [04:22<28:05,  6.46s/it]

R2: 0.7400832988395257  corr:  0.8622077914116675  pval:  0.0


 14%|█▍        | 42/300 [04:41<27:47,  6.46s/it]

R2: 0.7431792527258837  corr:  0.8637842772177113  pval:  0.0


 18%|█▊        | 55/300 [05:54<25:26,  6.23s/it]

R2: 0.7457639885176589  corr:  0.8655812196775192  pval:  0.0


 19%|█▊        | 56/300 [06:01<27:07,  6.67s/it]

R2: 0.7480283230983389  corr:  0.8674178065520624  pval:  0.0


 19%|█▉        | 58/300 [06:15<27:22,  6.79s/it]

R2: 0.7553978672771927  corr:  0.8711472245369256  pval:  0.0


 23%|██▎       | 68/300 [07:12<23:56,  6.19s/it]

R2: 0.7557772867100248  corr:  0.8702757065432302  pval:  0.0


 27%|██▋       | 80/300 [08:18<22:11,  6.05s/it]

R2: 0.7565023999482927  corr:  0.8720088829896512  pval:  0.0


 29%|██▉       | 88/300 [09:04<22:06,  6.26s/it]

R2: 0.7582871568496997  corr:  0.8722065897978775  pval:  0.0


 33%|███▎      | 99/300 [10:07<21:11,  6.32s/it]

R2: 0.7624582405897498  corr:  0.8756190172904509  pval:  0.0


  0%|          | 1/300 [00:07<37:27,  7.52s/it]

R2: -0.0030924802637992688  corr:  0.15901658342649885  pval:  0.0


  1%|          | 2/300 [00:15<39:10,  7.89s/it]

R2: 0.050039023479564904  corr:  0.4118409969982747  pval:  0.0


  1%|          | 3/300 [00:23<39:33,  7.99s/it]

R2: 0.15996746360457403  corr:  0.5530934164828504  pval:  0.0


  1%|▏         | 4/300 [00:31<39:14,  7.95s/it]

R2: 0.3840060038515499  corr:  0.7140647142458668  pval:  0.0


  2%|▏         | 5/300 [00:39<38:58,  7.93s/it]

R2: 0.5088129978530047  corr:  0.7657444662659517  pval:  0.0


  2%|▏         | 6/300 [00:47<38:45,  7.91s/it]

R2: 0.5859631510336181  corr:  0.7949843979564892  pval:  0.0


  2%|▏         | 7/300 [00:55<38:11,  7.82s/it]

R2: 0.6241382110303009  corr:  0.8105912209618412  pval:  0.0


  3%|▎         | 8/300 [01:02<37:31,  7.71s/it]

R2: 0.6394484399505271  corr:  0.8162574176223774  pval:  0.0


  3%|▎         | 9/300 [01:09<36:38,  7.55s/it]

R2: 0.6428550121872436  corr:  0.8175434241622694  pval:  0.0


  3%|▎         | 10/300 [01:17<36:31,  7.56s/it]

R2: 0.6437241190478098  corr:  0.8183833103356472  pval:  0.0


  4%|▎         | 11/300 [01:24<36:26,  7.56s/it]

R2: 0.6642728937295493  corr:  0.8193313599895975  pval:  0.0


  4%|▍         | 12/300 [01:32<36:42,  7.65s/it]

R2: 0.6692627870604948  corr:  0.8190602152031292  pval:  0.0


  4%|▍         | 13/300 [01:40<36:42,  7.67s/it]

R2: 0.6721619794922944  corr:  0.8234815891530829  pval:  0.0


  5%|▍         | 14/300 [01:48<36:59,  7.76s/it]

R2: 0.691341666404133  corr:  0.8339485746827368  pval:  0.0


  5%|▌         | 15/300 [01:55<36:17,  7.64s/it]

R2: 0.7026693707741986  corr:  0.8413031482430257  pval:  0.0


  5%|▌         | 16/300 [02:03<36:56,  7.80s/it]

R2: 0.7136348078334833  corr:  0.8453642142654232  pval:  0.0


  6%|▌         | 18/300 [02:17<34:51,  7.42s/it]

R2: 0.7184956658228105  corr:  0.8476805266321196  pval:  0.0


  6%|▋         | 19/300 [02:25<35:58,  7.68s/it]

R2: 0.7195730099455091  corr:  0.8493001048838702  pval:  0.0


  7%|▋         | 22/300 [02:47<36:03,  7.78s/it]

R2: 0.7230326572888925  corr:  0.8509659105880794  pval:  0.0


  9%|▉         | 28/300 [03:22<29:00,  6.40s/it]

R2: 0.7351247222375207  corr:  0.8583207260736878  pval:  0.0


 10%|█         | 30/300 [03:35<29:49,  6.63s/it]

R2: 0.7356690181326404  corr:  0.8581070249588325  pval:  0.0


 11%|█▏        | 34/300 [04:00<28:41,  6.47s/it]

R2: 0.7392627338024009  corr:  0.8613420241812687  pval:  0.0


 13%|█▎        | 38/300 [04:23<27:23,  6.27s/it]

R2: 0.7446089141788488  corr:  0.8638833277054487  pval:  0.0


 15%|█▍        | 44/300 [04:58<26:51,  6.30s/it]

R2: 0.7465597514509698  corr:  0.8651593972027262  pval:  0.0


 16%|█▌        | 48/300 [05:22<26:48,  6.38s/it]

R2: 0.7545461057361942  corr:  0.8698859981931046  pval:  0.0


 20%|██        | 60/300 [06:29<23:42,  5.93s/it]

R2: 0.7551064231664057  corr:  0.8703831177245256  pval:  0.0


 23%|██▎       | 69/300 [07:20<23:50,  6.19s/it]

R2: 0.758558301574689  corr:  0.8722595896888882  pval:  0.0


 26%|██▌       | 78/300 [08:11<23:13,  6.28s/it]

R2: 0.7650114712300224  corr:  0.8757675047073052  pval:  0.0


 29%|██▉       | 88/300 [09:07<21:22,  6.05s/it]

R2: 0.7660624207507205  corr:  0.8757743481503332  pval:  0.0


 30%|██▉       | 89/300 [09:15<23:13,  6.60s/it]

R2: 0.7664437212888837  corr:  0.877059839367916  pval:  0.0


 36%|███▋      | 109/300 [11:03<18:44,  5.89s/it]

R2: 0.7678711035007214  corr:  0.8776997536130805  pval:  0.0


 39%|███▉      | 118/300 [11:55<18:57,  6.25s/it]

R2: 0.7685982916097682  corr:  0.8772937034735929  pval:  0.0


100%|██████████| 300/300 [28:13<00:00,  5.64s/it]


R2 from the best models in each run are:
[0.76925564 0.76784907 0.7624617  0.76859775]
corr from the best models in each run are:
[0.87765357 0.87739345 0.87562212 0.87729587]


In [12]:
vi1 = 'div'

vo1 = 'ssh_cos'

save_fn_prefix  = 'any_{}_{}_smallbatch_cosonly_nobatchnorm'.format(vi1, vo1)
var_input_names = [vi1]
var_output_names = [vo1]

batch_size = 100

N_inp = len(var_input_names)
N_out = len(var_output_names)

lr0 = 0.005*10/batch_size #Roughly should scale inversely to batch_size

#Recording performance metrics on test data after eaching training cycle
R2_all = np.zeros(nensemble)
corr_all = np.zeros(nensemble)

nctrains, nctest = hf.load_data_from_nc_as_lists(root_dir)

all_train_input, all_train_output = preload_data_vortdiv(nctrains, Ntrain)
all_test_input, all_test_output = preload_data_vortdiv(nctest, Ntest)

#Normalize data
#Compute mean and variance for normalization
mean_input=np.nanmean(np.concatenate((all_train_input, all_test_input), axis=0),axis=(0, 2, 3))
mean_output=np.nanmean(np.concatenate((all_train_output, all_test_output), axis=0),axis=(0, 2, 3))
#Subtract the data with their means
all_train_input=all_train_input-mean_input[None, :, None, None]
all_train_output=all_train_output-mean_output[None, :, None, None]
all_test_input=all_test_input-mean_input[None, :, None, None]
all_test_output=all_test_output-mean_output[None, :, None, None]
#Compute the variances
var_input=np.nanmean((np.concatenate((all_train_input, all_test_input), axis=0))**2,axis=(0, 2, 3))
var_output=np.nanmean((np.concatenate((all_train_output, all_test_output), axis=0))**2,axis=(0, 2, 3))
print("mean and variance of all input data:")
print(mean_input,var_input)
print("mean and variance of all output data:")
print(mean_output,var_output)
#Scale the data so that they have variance of 1
all_train_input=all_train_input/np.sqrt(var_input[None, :, None, None])
all_train_output=all_train_output/np.sqrt(var_output[None, :, None, None])
all_test_input=all_test_input/np.sqrt(var_input[None, :, None, None])
all_test_output=all_test_output/np.sqrt(var_output[None, :, None, None])
#Have checked that after these operations, the data is scaled to be zero mean and variance 1.

for iensemble in np.arange(nensemble):
    run_model(var_input_names, var_output_names, save_fn_prefix, N_inp, N_out, iensemble, R2_all, corr_all)  
print('R2 from the best models in each run are:')
print(R2_all)
print('corr from the best models in each run are:')
print(corr_all)

mean and variance of all input data:
[3.2595452e-09] [3.62891008e-11]
mean and variance of all output data:
[-0.00051623] [9.36516511e-05]
Model has  1.124401  million params


  0%|          | 1/300 [00:05<29:38,  5.95s/it]

R2: -0.003531670180131119  corr:  0.0835755161125129  pval:  0.0


  1%|          | 2/300 [00:11<29:24,  5.92s/it]

R2: 0.001594867704651226  corr:  0.15529418134746084  pval:  0.0


  1%|▏         | 4/300 [00:23<28:36,  5.80s/it]

R2: 0.2616188056465576  corr:  0.6160627065066825  pval:  0.0


  2%|▏         | 5/300 [00:29<28:58,  5.89s/it]

R2: 0.5101169283823271  corr:  0.728428862271568  pval:  0.0


  2%|▏         | 6/300 [00:35<29:04,  5.93s/it]

R2: 0.5807526530910945  corr:  0.7632181083282771  pval:  0.0


  2%|▏         | 7/300 [00:41<29:14,  5.99s/it]

R2: 0.5931294908505182  corr:  0.7708550722807548  pval:  0.0


  3%|▎         | 8/300 [00:47<29:05,  5.98s/it]

R2: 0.611288683999536  corr:  0.7818615566895263  pval:  0.0


  3%|▎         | 9/300 [00:53<28:52,  5.95s/it]

R2: 0.6187074591718157  corr:  0.7867355922169563  pval:  0.0


  3%|▎         | 10/300 [00:59<28:59,  6.00s/it]

R2: 0.619066631925929  corr:  0.7869709760865737  pval:  0.0


  5%|▍         | 14/300 [01:18<24:52,  5.22s/it]

R2: 0.6369896974670715  corr:  0.8027212619365738  pval:  0.0


  6%|▌         | 17/300 [01:34<24:47,  5.26s/it]

R2: 0.6452389104565686  corr:  0.8115699704071507  pval:  0.0


  6%|▌         | 18/300 [01:40<25:51,  5.50s/it]

R2: 0.6495716824127094  corr:  0.8094452727988083  pval:  0.0


  6%|▋         | 19/300 [01:46<26:25,  5.64s/it]

R2: 0.6603223610246105  corr:  0.8148428676684623  pval:  0.0


  7%|▋         | 20/300 [01:52<26:45,  5.73s/it]

R2: 0.6622384512958452  corr:  0.8154850016446535  pval:  0.0


  8%|▊         | 25/300 [02:17<24:56,  5.44s/it]

R2: 0.6662396760314114  corr:  0.8175937204832205  pval:  0.0


 10%|▉         | 29/300 [02:38<23:50,  5.28s/it]

R2: 0.6713828335575691  corr:  0.8220176518854557  pval:  0.0


 10%|█         | 30/300 [02:44<24:46,  5.50s/it]

R2: 0.674299777943826  corr:  0.8236070096228596  pval:  0.0


 12%|█▏        | 37/300 [03:19<23:09,  5.28s/it]

R2: 0.689735649218557  corr:  0.8309202846178486  pval:  0.0


 13%|█▎        | 39/300 [03:29<22:39,  5.21s/it]

R2: 0.6907181197974801  corr:  0.8337707299172158  pval:  0.0


 15%|█▍        | 44/300 [03:53<20:49,  4.88s/it]

R2: 0.6940204538444489  corr:  0.8353661113914957  pval:  0.0


 19%|█▊        | 56/300 [04:47<19:44,  4.86s/it]

R2: 0.7009596367349785  corr:  0.8401558995049406  pval:  0.0


 19%|█▉        | 58/300 [04:57<20:08,  4.99s/it]

R2: 0.7015921421426876  corr:  0.8393522295627087  pval:  0.0


 20%|█▉        | 59/300 [05:03<20:54,  5.21s/it]

R2: 0.7023970227852303  corr:  0.8401448172789114  pval:  0.0


 23%|██▎       | 69/300 [05:51<19:08,  4.97s/it]

R2: 0.7032953984477088  corr:  0.8414843982752318  pval:  0.0


 23%|██▎       | 70/300 [05:56<20:02,  5.23s/it]

R2: 0.7038643304829495  corr:  0.8416815100298276  pval:  0.0


  0%|          | 1/300 [00:05<27:48,  5.58s/it]

R2: -0.058988976669506865  corr:  0.13941798777855635  pval:  0.0


  1%|          | 2/300 [00:11<29:00,  5.84s/it]

R2: -0.019045989619311143  corr:  0.1437640413182201  pval:  0.0


  1%|          | 3/300 [00:17<29:04,  5.87s/it]

R2: 0.006562522310200158  corr:  0.12708876602279784  pval:  0.0


  2%|▏         | 5/300 [00:28<27:41,  5.63s/it]

R2: 0.10980648009852989  corr:  0.43596005503277074  pval:  0.0


  2%|▏         | 6/300 [00:34<28:07,  5.74s/it]

R2: 0.40161003959925945  corr:  0.7021643788230417  pval:  0.0


  2%|▏         | 7/300 [00:40<28:20,  5.80s/it]

R2: 0.49318903643350465  corr:  0.7576877113243953  pval:  0.0


  3%|▎         | 8/300 [00:45<28:18,  5.82s/it]

R2: 0.5007987220995439  corr:  0.7595218174253744  pval:  0.0


  3%|▎         | 9/300 [00:51<28:01,  5.78s/it]

R2: 0.5042038539538887  corr:  0.7618766501955989  pval:  0.0


  4%|▍         | 13/300 [01:11<25:12,  5.27s/it]

R2: 0.5223809814900706  corr:  0.7512998193556026  pval:  0.0


  5%|▍         | 14/300 [01:17<25:58,  5.45s/it]

R2: 0.589952075911422  corr:  0.7793637280250862  pval:  0.0


  5%|▌         | 15/300 [01:22<26:18,  5.54s/it]

R2: 0.5990578157542681  corr:  0.7801428796034784  pval:  0.0


  7%|▋         | 22/300 [01:56<23:41,  5.11s/it]

R2: 0.6102805090794754  corr:  0.8013911705115981  pval:  0.0


  8%|▊         | 23/300 [02:02<24:24,  5.29s/it]

R2: 0.6333927973380071  corr:  0.8060009975712077  pval:  0.0


  9%|▉         | 27/300 [02:21<22:52,  5.03s/it]

R2: 0.6352860285092801  corr:  0.8066234938569603  pval:  0.0


  9%|▉         | 28/300 [02:27<23:32,  5.19s/it]

R2: 0.6485401306592284  corr:  0.8115868890857267  pval:  0.0


 10%|▉         | 29/300 [02:33<24:04,  5.33s/it]

R2: 0.6589555804302945  corr:  0.8175812998172908  pval:  0.0


 12%|█▏        | 36/300 [03:07<22:29,  5.11s/it]

R2: 0.6711379130117874  corr:  0.8195144417177818  pval:  0.0


 13%|█▎        | 38/300 [03:17<23:09,  5.30s/it]

R2: 0.6747588949392557  corr:  0.8259604638385433  pval:  0.0


 16%|█▋        | 49/300 [04:09<20:10,  4.82s/it]

R2: 0.680529323112607  corr:  0.8270408558027036  pval:  0.0


 17%|█▋        | 51/300 [04:19<20:39,  4.98s/it]

R2: 0.6846021680197993  corr:  0.8274226440117067  pval:  0.0


 18%|█▊        | 53/300 [04:30<21:06,  5.13s/it]

R2: 0.6853190245364044  corr:  0.8290502206549667  pval:  0.0


 19%|█▉        | 58/300 [04:54<20:09,  5.00s/it]

R2: 0.6948373721023647  corr:  0.8356687402674577  pval:  0.0


 25%|██▌       | 75/300 [06:12<18:09,  4.84s/it]

R2: 0.697711380006128  corr:  0.8376517892567663  pval:  0.0


 30%|██▉       | 89/300 [07:17<17:23,  4.95s/it]

R2: 0.697862785619886  corr:  0.8383815445572449  pval:  0.0


  0%|          | 1/300 [00:05<28:32,  5.73s/it]

R2: -0.03823158507417945  corr:  0.15295544620403453  pval:  0.0


  1%|          | 2/300 [00:11<28:38,  5.77s/it]

R2: -0.022218406665027057  corr:  0.15778710147972075  pval:  0.0


  1%|          | 3/300 [00:17<28:06,  5.68s/it]

R2: 0.08493987959248983  corr:  0.512391776598878  pval:  0.0


  1%|▏         | 4/300 [00:22<27:53,  5.66s/it]

R2: 0.2950591073970884  corr:  0.6093651021746341  pval:  0.0


  2%|▏         | 5/300 [00:28<27:48,  5.66s/it]

R2: 0.47587536047359935  corr:  0.7206174507682033  pval:  0.0


  2%|▏         | 6/300 [00:33<27:27,  5.60s/it]

R2: 0.5470246702824515  corr:  0.75520523964233  pval:  0.0


  2%|▏         | 7/300 [00:39<27:46,  5.69s/it]

R2: 0.5801410682143213  corr:  0.7784983708218665  pval:  0.0


  5%|▌         | 15/300 [01:17<23:50,  5.02s/it]

R2: 0.626741223062803  corr:  0.7981865196288384  pval:  0.0


  6%|▌         | 17/300 [01:28<24:42,  5.24s/it]

R2: 0.6366271266927359  corr:  0.8024117604823257  pval:  0.0


  7%|▋         | 21/300 [01:47<23:38,  5.08s/it]

R2: 0.6454830146703876  corr:  0.8140430382493343  pval:  0.0


  8%|▊         | 23/300 [01:57<23:50,  5.16s/it]

R2: 0.6522527824571871  corr:  0.8102489586420045  pval:  0.0


  8%|▊         | 24/300 [02:03<24:42,  5.37s/it]

R2: 0.653851820555133  corr:  0.8142183128851344  pval:  0.0


  8%|▊         | 25/300 [02:09<25:04,  5.47s/it]

R2: 0.6614597273013483  corr:  0.8140022906870737  pval:  0.0


  9%|▊         | 26/300 [02:15<25:13,  5.53s/it]

R2: 0.6623238347105386  corr:  0.8193870413328311  pval:  0.0


  9%|▉         | 28/300 [02:25<24:34,  5.42s/it]

R2: 0.6718564706374365  corr:  0.822250256566899  pval:  0.0


 10%|▉         | 29/300 [02:31<24:58,  5.53s/it]

R2: 0.6771245377581894  corr:  0.8243928741359865  pval:  0.0


 12%|█▏        | 37/300 [03:08<21:33,  4.92s/it]

R2: 0.6811914685770888  corr:  0.8291377081898458  pval:  0.0


 13%|█▎        | 39/300 [03:18<22:09,  5.10s/it]

R2: 0.6834824533502026  corr:  0.8290678300749175  pval:  0.0


 13%|█▎        | 40/300 [03:24<23:01,  5.31s/it]

R2: 0.6840320347091293  corr:  0.8295834204286929  pval:  0.0


 16%|█▌        | 47/300 [03:58<21:22,  5.07s/it]

R2: 0.68699918343987  corr:  0.8343668045313447  pval:  0.0


 16%|█▋        | 49/300 [04:08<21:05,  5.04s/it]

R2: 0.6907130253242157  corr:  0.8337276192067661  pval:  0.0


 18%|█▊        | 55/300 [04:37<20:18,  4.97s/it]

R2: 0.7041308767007803  corr:  0.8400779562077937  pval:  0.0


  0%|          | 1/300 [00:06<30:04,  6.03s/it]

R2: 0.0014025390783164449  corr:  0.14052614121146967  pval:  0.0


  1%|          | 2/300 [00:12<29:50,  6.01s/it]

R2: 0.026990563188291072  corr:  0.25247960466150465  pval:  0.0


  1%|          | 3/300 [00:17<29:13,  5.90s/it]

R2: 0.16306577386414622  corr:  0.5432159426876761  pval:  0.0


  1%|▏         | 4/300 [00:23<28:54,  5.86s/it]

R2: 0.34131771582772863  corr:  0.5956278614073977  pval:  0.0


  2%|▏         | 5/300 [00:29<28:31,  5.80s/it]

R2: 0.5382161284068643  corr:  0.7417570691765762  pval:  0.0


  2%|▏         | 6/300 [00:35<28:17,  5.77s/it]

R2: 0.6137875541498518  corr:  0.7863106987677454  pval:  0.0


  2%|▏         | 7/300 [00:41<28:32,  5.85s/it]

R2: 0.632388244226546  corr:  0.7953449653890303  pval:  0.0


  3%|▎         | 8/300 [00:46<28:19,  5.82s/it]

R2: 0.640763034793645  corr:  0.8024793333178151  pval:  0.0


  3%|▎         | 9/300 [00:52<28:12,  5.82s/it]

R2: 0.6421942675327804  corr:  0.8034285924086007  pval:  0.0


  3%|▎         | 10/300 [00:58<28:01,  5.80s/it]

R2: 0.6422983492189231  corr:  0.8037191913814121  pval:  0.0


  5%|▌         | 16/300 [01:27<24:12,  5.12s/it]

R2: 0.6423301572733624  corr:  0.8095308778935846  pval:  0.0


  6%|▌         | 18/300 [01:37<24:25,  5.20s/it]

R2: 0.6468408001991337  corr:  0.8115768343873906  pval:  0.0


  6%|▋         | 19/300 [01:43<25:37,  5.47s/it]

R2: 0.6473663801550532  corr:  0.8100365708879899  pval:  0.0


  7%|▋         | 20/300 [01:49<25:57,  5.56s/it]

R2: 0.651194410816488  corr:  0.8120748250014329  pval:  0.0


  8%|▊         | 25/300 [02:14<24:07,  5.26s/it]

R2: 0.6540574336621673  corr:  0.8120307177350716  pval:  0.0


  9%|▉         | 27/300 [02:25<24:19,  5.35s/it]

R2: 0.6716807590963144  corr:  0.8242399854843064  pval:  0.0


 10%|▉         | 29/300 [02:35<24:17,  5.38s/it]

R2: 0.6745028123186783  corr:  0.8249986068326931  pval:  0.0


 11%|█         | 33/300 [02:55<23:04,  5.18s/it]

R2: 0.6809744806075634  corr:  0.8264249615206957  pval:  0.0


 15%|█▌        | 45/300 [03:53<23:27,  5.52s/it]

R2: 0.6822988470113764  corr:  0.8290911725077789  pval:  0.0


 16%|█▌        | 48/300 [04:08<22:22,  5.33s/it]

R2: 0.6872050016601622  corr:  0.8322308484177514  pval:  0.0


 17%|█▋        | 51/300 [04:23<21:35,  5.20s/it]

R2: 0.6881343706629435  corr:  0.8325905295249125  pval:  0.0


 17%|█▋        | 52/300 [04:29<22:13,  5.38s/it]

R2: 0.6950110770180709  corr:  0.8376715986141466  pval:  0.0


100%|██████████| 300/300 [23:03<00:00,  4.61s/it]


R2 from the best models in each run are:
[0.70388961 0.69786856 0.70412668 0.69500771]
corr from the best models in each run are:
[0.84168713 0.83839298 0.84008428 0.83767132]
